### ISSUE TITLE
JsonParserTester.RunTests unit test aborts

### ISSUE THREAD

**Issue by yugoren** [aws/aws-iot-device-sdk-cpp#1]
After a fresh pull and successful compile, `./bin/aws-iot-unit-tests`  aborts with the following message:
```
aws-iot-device-sdk-cpp/src/tests/unit/src/util/JsonParserTests.cpp:140: Failure
      Expected: ResponseCode::SUCCESS
      Which is: 4-byte object <00-00 00-00>
To be equal to: rc
      Which is: 4-byte object <9C-FF FF-FF>
aws-iot-unit-tests: aws-iot-device-sdk-cpp/bin/third_party/rapidjson/src/include/rapidjson/document.h:1128: rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberEnd() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::ConstMemberIterator = rapidjson::GenericMemberIterator<true, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]: Assertion `IsObject()' failed.
Aborted
```

**Comment by vareddy** [comment]
Hi @yugoren,
Thank you for using AWS IoT! 
We are unable to reproduce the error. We think it might be an access permissions issue or the unit tests are being run from a path they did not expect. 
Could you cd into `aws-iot-device-sdk-cpp/build/bin` and then run `./aws-iot-unit-tests` ?
Please let us know if you have any more questions. 
Thanks!
Varun

**Comment by yugoren** [comment]
Hi @vareddy,

You were exactly right! I was running the executable at the top of build directory (`./bin/aws-iot-unit-tests`). Now that I `cd` into the folder, it works with no errors/aborts.

Thanks a lot,
Yusuf
