### ISSUE TITLE
‘SDK_VERSION_STRING’ was not declared in this scope

### ISSUE THREAD

**Issue by nagarajec** [aws/aws-iot-device-sdk-cpp#102]
Trying to build lib for my iot project, where should I define SDK_VERSION_STRING?

**Comment by vareddy** [comment]
Hi @nagarajec,
The SDK_VERSION_STRING is defined in the [CMakeLists.txt](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/CMakeLists.txt#L50). If you are using a custom CMakeList, you will have to define it there or pass it in as a command line parameter when running cmake. 
Please let us know if you have any more questions and thank you for your interest in the AWS IoT SDK.
Varun

**Comment by nagarajec** [comment]
Hi @vareddy ,
I am trying to build library including my client code, I have included aws sdk cpp source files in makefile. In this case how to include the version?

**Comment by vareddy** [comment]
Hi @nagarajec,
Are you using CMake? If yes, then add this line in the CMakeLists.txt:
`add_definitions(-DSDK_VERSION_STRING="1.4.0")`
If you are using just make, you can see if any of the answers [here](https://stackoverflow.com/questions/2826029/passing-additional-variables-from-command-line-to-make) allow you to provide runtime arguments.
Thanks!
Varun

**Comment by vareddy** [comment]
Hi @nagarajec,
Were you able to resolve this issue? If so please close this issue.
Thanks!
Varun

**Comment by vareddy** [comment]
Hi @nagarajec,
This issue has been inactive for a long time so we are closing it. Please open a new issue if you encounter any more problems. 
Thanks!
Varun

**Comment by shiftreg** [comment]
I have the same problem but i built everything by default. When i open the built project in Eclipse i always getting the Problem with "SDK_VERSION_STRING". I have to add that Im completly new to cmake and added the include paths in Eclipse manually until "SDK_VERSION_STRING" could not resolved. Do i need to define it manually in the header where its missing?
