### ISSUE TITLE
Device/system requirements for aws iot sdk cpp

### ISSUE THREAD

**Issue by nagarajec** [aws/aws-iot-device-sdk-cpp#103]
Hi,

To use aws iot sdk cpp libary with all features, anybody knows the device hardware/software requirements? 
Like, 
1.	RAM requirements
2.	Flash requirements
3.	Processor Throughput

Appreciate your response.

**Comment by vareddy** [comment]
Hi @nagarajec,
This SDK was not designed keeping resource constrained systems in mind and as such we don't have specific values we can provide for the above requirements. If you need to use the SDK with a very resource constrained system, the AWS IoT SDK for C would be a better candidate. 
The requirements for this SDK are more related to the whether the OS has threading enabled and if the specified SSL layer is supported. We have tested this SDK on a number of Linux based systems, such as the Raspberry Pi, with no issues. 
If you're also compiling on said system, it will need to support GCC 5+ and have all dependencies installed, as can be seen on in the [Platform.md](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/Platform.md) page. 
Please let us know if you have any more questions.
Thanks!
Varun

**Comment by nagarajec** [comment]
Thank you
