### ISSUE TITLE
Build file to use

### ISSUE THREAD

**Issue by nagarajec** [aws/aws-iot-device-sdk-cpp#104]
Which build file to use along with my client application in makefile? I have got archive folder and bin folder when I build the sdk. Each have libaws-iot-sdk-cpp.a and aws-iot files. Among these which one should I use to link in makefile? 

Appreciate your response.

**Comment by vareddy** [comment]
Hi @nagarajec,
The `aws-iot` is an application binary, it contains the CLI application and is not the library file. `libaws-iot-sdk-cpp.a` is the static library. You can link to one in the archive folder. Conversely, you can also run `sudo make install`, which will install it in your system's lib directory. 
Please let us know if you have any more questions.
Thanks!
Varun

**Comment by nagarajec** [comment]
Do I need to run sudo make install from build directory?

**Comment by vareddy** [comment]
Yes, this should be run in the `build` directory.
Thanks!
Varun

**Comment by nagarajec** [comment]
Hi @vareddy,
Thanks for the response, able to clear few issues. How about rapidjson? When I run makefile I am getting below error. 
g++ -c -std=c++11 da_iot_sdk_lib.cpp -o da_iot_sdk_lib.o -DENABLE_IOT_DEBUG -DENABLE_IOT_INFO -DENABLE_IOT_WARN -DENABLE_IOT_ERROR -lcurl  -I . -Iusr/local/include -Lusr/local/lib/libaws-iot-sdk-cpp.a -Lusr/local/lib/rapidjson
da_iot_sdk_lib.cpp:15:38: fatal error: rapidjson/filereadstream.h: No such file or directory
 #include <rapidjson/filereadstream.h>

In my client application I have included as below:
#include <rapidjson/filereadstream.h>
#include <rapidjson/filewritestream.h>
#include <rapidjson/stringbuffer.h>
#include <rapidjson/writer.h>

**Comment by nagarajec** [comment]
Do I need to copy the rapidjson from third_party folder to usr/local/lib folder?

**Comment by vareddy** [comment]
If you are using RapidJSON in your application, you will also have to install it in a similar manner to the lib directory. Either copy it, or install it as stated in their [README](https://github.com/Tencent/rapidjson).
Thanks!
Varun

**Comment by nagarajec** [comment]
Thanks Varun, I have resolved rapidjson issue by copying to src directory. But I am getting ResponseCode issue as below. I know ResponseCode.hpp is being included in multiple files but I need to include those files as well. How can I resolve this? I am sorry If I am bothering too much!

In file included from /usr/local/include/mqtt/Common.hpp:25:0,
                 from /usr/local/include/mqtt/ClientState.hpp:32,
                 from /usr/local/include/mqtt/Connect.hpp:24,
                 from /usr/local/include/mqtt/Client.hpp:31,
                 from da_iot_sdk_lib.cpp:11:
./ResponseCode.hpp:41:16: error: multiple definition of ‘enum class awsiotsdk::ResponseCode’
     enum class ResponseCode {
                ^
In file included from /usr/local/include/NetworkConnection.hpp:35:0,
                 from /usr/local/include/util/threading/ThreadTask.hpp:30,
                 from /usr/local/include/Action.hpp:33,
                 from /usr/local/include/ClientCoreState.hpp:33,
                 from /usr/local/include/ClientCore.hpp:29,
                 from /usr/local/include/mqtt/Client.hpp:29,
                 from da_iot_sdk_lib.cpp:11:
/usr/local/include/ResponseCode.hpp:41:16: note: previous definition here
     enum class ResponseCode {

**Comment by nagarajec** [comment]
To add to the above, I have used #include "mqtt/Client.hpp" in my source file thats it.

**Comment by nagarajec** [comment]
Hi @vareddy 
After analyzing the issue in SDK Client.hpp has ClientCore and Connect headers which in turn includes ResponseCode.h both. Looks like a circular dependency here. This is in SDK itself. To have NetworkConnection and Mqtt features which header file I need to include instead of mqtt/Client.hpp?

**Comment by vareddy** [comment]
Could you paste the includes which you are using in your application here? Might be some conflict as to which files are being included.
Also what is the directory structure of where your application is located? I just want check if that might be interfering. 
Thanks!
Varun

**Comment by nagarajec** [comment]
@vareddy 
My requirement is using iot sdk cpp to connect iot cloud for device registration, status check and publish messages through mqtt. But I am struggling to understand how to use sdk!!!

**Comment by vareddy** [comment]
Hi @nagarajec,
Were you able to solve this issue? Also when you say "include sample's PubSub code in our client", would you like to use code from the sample directly in your client code or convert the sample itself into a part of the library and use it?
Thanks!
Varun

**Comment by nagarajec** [comment]
I am able to solve the issue. Thank you!
