### ISSUE TITLE
Network Layer Implementation clarification

### ISSUE THREAD

**Issue by Maurizio1** [aws/aws-iot-device-sdk-cpp#105]
Would you clarify the following sentence (in
Network Layer Implementation Guide): 
```The Network Base class defines the following functions that **"are"** a Concrete implementation **"is"** required to provide.```
I don't clearly get the correct meaning.

**Comment by vareddy** [comment]
Hi @Maurizio1,
The above statement has a typo, it should read:
``` The Network Base class defines the following functions that a Concrete implementation is required to provide.```
It means that if you create a custom network class, the listed virtual functions should be implemented by your custom class. Any other internal functions can be present but the following functions are essential for the SDK to compile and work correctly. As can be seen in [OpenSSLConnection.hpp](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/network/OpenSSL/OpenSSLConnection.hpp#L84), [WebSocketConnection.hpp](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/network/WebSocket/WebSocketConnection.hpp#L47) and [MbedTLSConnection.hpp](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/network/MbedTLS/MbedTLSConnection.hpp#L48), they all inherit the [NetworkConnection.hpp](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/include/NetworkConnection.hpp) base class and implement said virtual functions.
Thank you for your interest in the AWS IoT SDK and let us know if you have any more questions. 
Varun

**Comment by Maurizio1** [comment]
OK.
Thanks
