### ISSUE TITLE
Calling methods from outside app

### ISSUE THREAD

**Issue by nagarajec** [aws/aws-iot-device-sdk-cpp#106]
Hi @vareddy,
I have included sdk with my custom client code and build the static library out of it. Now I want to test with another stand alone test class file just to execute the methods in my static lib. But  its giving me undefined methods error. Below is my make file wherein I am linking the static lib. Could you please let me know what might be the issue? I have a header file along with my stand alone class which has methods defined. libDAIoTSDK is my sdk lib along with client code.
----------------------------
CXX=g++
SYS_HEADER_DIR = /usr/local/include/
APP_DIR = ./
APP_NAME = main_body_pub
APP_C_FILES = $(APP_DIR)$(APP_NAME).cpp
APP_H_FILES = $(APP_DIR)da_iot_device_sdk.h $(APP_DIR)PubSub.hpp  $(SYS_HEADER_DIR)/curl/curl.h
STATIC_LIBS_DIR = ./
STATIC_LIBS = ./libDAIoTSDK.a -lcurl -lmbedtls -lmbedcrypto -lmbedx509
SOURCES = $(APP_C_FILES) $(APP_H_FILES) $(STATIC_LIBS)

$(APP_NAME):$(SOURCES)
        $(CXX) -std=c++11 -o $@ $(APP_C_FILES) $(STATIC_LIBS)
-------------------------

**Comment by nagarajec** [comment]
methods are from my client code which in turn built along with sdk source files.

**Comment by JonathanHenson** [comment]
We'd need compiler output and also see your build script and some code to be any help here. Please reopen if you have further info.
