### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by nagarajec** [aws/aws-iot-device-sdk-cpp#107]
Hi @vareddy ,

I am getting undefined reference for  `pthread_create' in clientcore.cpp. Below is the stacktrace. I was not able to find any method with the name in sdk. Any idea?

./libDAIoTSDK.a(ClientCore.o): In function `std::thread::thread<std::_Bind<std::_Mem_fn<void (awsiotsdk::ClientCoreState::*)(std::shared_ptr<std::atomic<bool> >)> (std::shared_ptr<awsiotsdk::ClientCoreState>, std::shared_ptr<std::atomic<bool> >)>>(std::_Bind<std::_Mem_fn<void (awsiotsdk::ClientCoreState::*)(std::shared_ptr<std::atomic<bool> >)> (std::shared_ptr<awsiotsdk::ClientCoreState>, std::shared_ptr<std::atomic<bool> >)>&&)':
ClientCore.cpp:(.text._ZNSt6threadC2ISt5_BindIFSt7_Mem_fnIMN9awsiotsdk15ClientCoreStateEFvSt10shared_ptrISt6atomicIbEEEES5_IS4_ES8_EEJEEEOT_DpOT0_[_ZNSt6threadC5ISt5_BindIFSt7_Mem_fnIMN9awsiotsdk15ClientCoreStateEFvSt10shared_ptrISt6atomicIbEEEES5_IS4_ES8_EEJEEEOT_DpOT0_]+0x7d): undefined reference to `pthread_create'
./libDAIoTSDK.a(ClientCore.o): In function `std::thread::thread<std::_Bind<std::_Mem_fn<awsiotsdk::ResponseCode (awsiotsdk::Action::*)(std::shared_ptr<awsiotsdk::NetworkConnection>, std::shared_ptr<awsiotsdk::ActionData>)> (std::unique_ptr<awsiotsdk::Action, std::default_delete<awsiotsdk::Action> >, std::shared_ptr<awsiotsdk::NetworkConnection>, std::shared_ptr<awsiotsdk::ActionData>)>>(std::_Bind<std::_Mem_fn<awsiotsdk::ResponseCode (awsiotsdk::Action::*)(std::shared_ptr<awsiotsdk::NetworkConnection>, std::shared_ptr<awsiotsdk::ActionData>)> (std::unique_ptr<awsiotsdk::Action, std::default_delete<awsiotsdk::Action> >, std::shared_ptr<awsiotsdk::NetworkConnection>, std::shared_ptr<awsiotsdk::ActionData>)>&&)':
ClientCore.cpp:(.text._ZNSt6threadC2ISt5_BindIFSt7_Mem_fnIMN9awsiotsdk6ActionEFNS3_12ResponseCodeESt10shared_ptrINS3_17NetworkConnectionEES6_INS3_10ActionDataEEEESt10unique_ptrIS4_St14default_deleteIS4_EES8_SA_EEJEEEOT_DpOT0_[_ZNSt6threadC5ISt5_BindIFSt7_Mem_fnIMN9awsiotsdk6ActionEFNS3_12ResponseCodeESt10shared_ptrINS3_17NetworkConnectionEES6_INS3_10ActionDataEEEESt10unique_ptrIS4_St14default_deleteIS4_EES8_SA_EEJEEEOT_DpOT0_]+0x7d): undefined reference to `pthread_create'

**Comment by vareddy** [comment]
Hi @nagarajec,
You need to link with the pthread library while compiling (ie. add the -lpthread in the make file) while compiling. Let me know if that works.
Also, a general suggestion, please close issues that have been resolved. Opening new issues for each separate problem is a good practice but this leads to many issues that become stagnant if they have been resolved but not closed. 
Thanks!
Varn

**Comment by nagarajec** [comment]
resolved using other methods
