### ISSUE TITLE
SDK error while initializing common in pubsub

### ISSUE THREAD

**Issue by nagarajec** [aws/aws-iot-device-sdk-cpp#109]
Hi @vareddy,

While running the pubsub I am getting the below error, I see the config folder under bin directory and SampleConfig.json file also present. Could you please let me know what might went wrong?

[ERROR] Mon Jul  2 20:38:46 2018
:666 [Sample Config] [139709260732224] [InitializeCommon:L140] : Error in Parsing. Error occurred while trying to open the file : SDK Code -100.
 parse error code : 0, offset : 0

I am using my other location to store certs. Below are the values in SampleConfig.json
 "root_ca_relative_path": "/home/ubuntu/app_private/certs/rootCA.crt",
  "device_certificate_relative_path": "/home/ubuntu/app_private/certs/cert.pem",
  "device_private_key_relative_path": "/home/ubuntu/app_private/certs/privkey.pem"

**Comment by vareddy** [comment]
Hi @nagarajec,
That error could be caused due to an improperly constructed JSON. Could you take the ```SampleConfig.json``` and run it through a linter to check if there are any errors in the config? Something like this perhaps: https://jsonlint.com/ 
Thanks!
Varun

**Comment by nagarajec** [comment]
@vareddy ,
I ran through validator but its a valid JSON. Any other thoughts?

**Comment by vareddy** [comment]
Hi @nagarajec,
In my testing, the error exact error was thrown when the file containing the config is not found. The file name and location should be correctly specified on this [line](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/samples/PubSub/PubSub.cpp#L314). Could you please confirm if that is correctly specified?
Thanks!
Varun

**Comment by nagarajec** [comment]
Thank you!
