### ISSUE TITLE
Undefine reference to anything in the ConfigCommon.hpp file

### ISSUE THREAD

**Issue by mnelson920** [aws/aws-iot-device-sdk-cpp#11]
I'm trying to compile my version of the shadowDelta sample and after getting the cmake file set up properly. I run into a error during make: "undefined reference to awsiotsdk::ConfigCommon::" then anything that was called from that file. I know its not an issue with the SDK because nobody else I seen had any problems with it but I cannot get this to compile. Any help would be appreciated.

**Comment by vareddy** [comment]
Hi @mnelson920,
Thank you for your interest in the AWS IoT SDK!
Could you compare your makefile with that of the ShadowDelta sample and ensure that it is correct:

1. The common files need to be included correctly in the add executable and target_include_directories statements. 
```
 # Add Target
add_executable(${SHADOW_DELTA_SAMPLE_TARGET_NAME} "${PROJECT_SOURCE_DIR}/ShadowDelta.cpp;${PROJECT_SOURCE_DIR}/../../common/ConfigCommon.cpp")

# Add Target specific includes
target_include_directories(${SHADOW_DELTA_SAMPLE_TARGET_NAME} PUBLIC ${PROJECT_SOURCE_DIR}/../../common)
```

2.  If compiling on Windows, using Visual Studio:
```
target_sources(${SHADOW_DELTA_SAMPLE_TARGET_NAME} PUBLIC ${PROJECT_SOURCE_DIR}/../../common/ConfigCommon.hpp)
    source_group("Header Files\\Samples\\ShadowDelta" FILES ${PROJECT_SOURCE_DIR}/../../common/ConfigCommon.hpp)
    source_group("Source Files\\Samples\\ShadowDelta" FILES ${PROJECT_SOURCE_DIR}/../../common/ConfigCommon.cpp)
```
Please let us know if you have any more issues.

Thanks,
Varun

**Comment by mnelson920** [comment]
That work thank you very much.

Mark
