### ISSUE TITLE
Certificate id creation

### ISSUE THREAD

**Issue by nagarajec** [aws/aws-iot-device-sdk-cpp#111]
Hi @vareddy,
Could you please let me know how to create certificate id from console for thing? I know when we create a thing, we can create private, public and certificate for a device along with root crt. But through client when we do createKeysAndCertificate, we get certificate id also. Why can't we get through console as well?

**Comment by vareddy** [comment]
Hi @nagarajec,
The certificate ID is basically the subject CN of the certificate. When you download the certificate from the console, you can run 
``` openssl x509 -in <certificate.pem.crt>-text -noout```
and look for the line that says ```Subject: CN=AWS IoT Certificate```. This is going to be common for all certificates generated by AWS IoT. 
More information can be found [here](https://docs.aws.amazon.com/cli/latest/reference/iot/create-keys-and-certificate.html), where it says:
```The ID of the certificate. AWS IoT issues a default subject name for the certificate (for example, AWS IoT Certificate).```
Let us know if that makes sense.
Thanks!
Varun

**Comment by nagarajec** [comment]
Thanks!!
