### ISSUE TITLE
Sample application include in aws static lib

### ISSUE THREAD

**Issue by nagarajec** [aws/aws-iot-device-sdk-cpp#113]
Hi All,
I have below questions:
1. I have added addFunction() **(for testing purpose)** method in PubSub.cpp under samples/pubsub/pubsub.cpp file and complied and build the static library using makefile, the lib in pubsub/archive/ libaws-iot-sdk-cpp.a should contain the changes of pubsub.cpp correct? 
2. I have another application uses this static lib and I am trying to call method addFunction() in static lib (libaws-iot-sdk-cpp.a) but I am getting below errors. So How can I call anyfunctions in sdk library from third party applications?

**./main_body_pub_test.cpp:16:11: error: ‘addFunction’ is not a member of ‘awsiotsdk::samples’
   int a = awsiotsdk::samples::addFunction(4,6);**

main_body_pub_test.cpp:
_#include <iostream>
#include <cstring>
#include "PubSub.hpp"
int main(int argc, char **argv) {
int a = awsiotsdk::samples::addFunction(4,6);
  printf("Result :%i\n",a);
}_

PubSub.hpp:
_#pragma once
namespace awsiotsdk {
  namespace samples {
        class PubSub {
          public:
            int addFunction(int a, int b);
         };
    }
}_

MakeFile:
_CXX=g++
SYS_HEADER_DIR = /usr/local/include/
APP_DIR = ./
APP_NAME = main_body_pub_test
APP_C_FILES = $(APP_DIR)$(APP_NAME).cpp
APP_H_FILES = $(APP_DIR)PubSub.hpp  $(SYS_HEADER_DIR)/curl/curl.h
STATIC_LIBS_DIR = ./
STATIC_LIBS = ./libaws-iot-sdk-cpp.a -lcurl -lmbedtls -lmbedcrypto -lmbedx509
SOURCES = $(APP_C_FILES) $(APP_H_FILES) $(STATIC_LIBS)
$(APP_NAME):$(SOURCES)
	$(CXX) -std=c++11 -o $@ $(APP_C_FILES) $(STATIC_LIBS)_

**Comment by nagarajec** [comment]
@vareddy could you please clarify? thoughts?

**Comment by JonathanHenson** [comment]
Could you try?

```int main(int argc, char **argv) {
    awsiotsdk::samples::PubSub pubSub;
    int a = pubSub.addFunction(4, 6);
    printf("Result :%i\n",a);
}```

**Comment by swatinair1234** [comment]
Hi Nagaraj ,
I am working on the PubSub in samples. I havent created any separate main.cpp. I am trying the example in PubSub.cpp. I am trying to build it . But its giving me errors like OpenSSLConnection.hpp is not found inspite of adding the include files.This is my task.json file
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build",
            "command": "g++",
            "args": [
                "-g",
                "PubSub.cpp",
                "libaws-iot-sdk-cpp.a"
                
            ],
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
}
Please let me know if i have to add any other static libs or so .Thanks in advance
