### ISSUE TITLE
Obtaining session token using registered IoT Certificates

### ISSUE THREAD

**Issue by SomeshDaga** [aws/aws-iot-device-sdk-cpp#115]
Hi.

Does the SDK expose any methods for obtaining temporary AWS credentials using certificates registered for a thing? The core aws sdk cpp does not seem to provide this functionality from what I could see. It'd be nice to not have to create an IAM user to obtain temporary credentials.

The iot javascript SDK (https://github.com/aws/aws-iot-device-sdk-js#device) provides a method to initialize an IoT session with a thing:

```
var device = awsIot.device({
   keyPath: <YourPrivateKeyPath>,
  certPath: <YourCertificatePath>,
    caPath: <YourRootCACertificatePath>,
  clientId: <YourUniqueClientIdentifier>,
      host: <YourCustomEndpoint>
});
```

I was hoping there would be a similar way using the cpp sdk. However, I think there's value in separating the generation of the temporary credentials and the initialization of the IoT session with those credentials, as a device may have multiple AWS services that are exposed via the role alias, and the different services may be handled in separate processes sharing the same set of credentials.

**Comment by ColdenCullen** [comment]
Would you be using it for opening connections with mutual TLS? If not, the consensus around here seems to be that your best bet would be to use traditional AWS auth methods.

**Comment by SomeshDaga** [comment]
Thanks. After gaining a bit more familiarity with the workings of AWS and the SDKs, I see the error of my ways.
