### ISSUE TITLE
MqttClient::Connect ignores action timeout and blocks

### ISSUE THREAD

**Issue by certabitmh** [aws/aws-iot-device-sdk-cpp#118]
Hello,

When calling (Mqtt) Client::Connect(), it blocks the application (as described in doc -> ok) but ignores action timeout. Tried with default ConfigCommon::mqtt_command_timeout_ of 20000msecs and reduced of 3000ms.

[https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Client.cpp]

I'm using release 1.4.0

**Comment by certabitmh** [comment]
seems that it's related to timing, if I set the timeout to 10 (should be msec) then Connect returns after somewhat 20 sec...
do I have to adjust any timing methods to my platform (arm + emb. linux)?

**Comment by graebm** [comment]
I'm not seeing the behavior you're describing. I ran the `pub-sub-sample` on an OSX machine. I set `mqtt_command_timeout_msecs` to 3000 in `SampleConfig.json`. Connect() returned after 3 seconds with a timeout error. I tried setting it to 10 and the timeout happened immediately.

Digging into the implementation, the code which holds up the main thread for N milliseconds is this line:
`aws-iot-device-sdk-cpp/src/ClientCoreState.cpp` line 123
It's a call to `std::condition_variable::wait_for()` and the wait time is passed as `std::chrono::milliseconds`.
That's all standard library stuff. I *hope* it's implemented correctly on Arm Embedded Linux.

Are you sure that you're actually changing `ConfigCommon::mqtt_command_timeout_`? Can you set a breakpoint and confirm? Or print out its value?

**Comment by certabitmh** [comment]
Hi graebm,
yes I directly used different values as function paramter of connect instead of `ConfigCommon::mqtt_command_timeout` and placed the execution in an own thread to ensure nothing else blocks it...

**Comment by certabitmh** [comment]
by directly passing the timeout parameter (2000) when calling connect:

`rc = _pMqttClient->Connect(2000,
                ConfigCommon::is_clean_session_,
                mqtt::Version::MQTT_3_1_1,
                ConfigCommon::keep_alive_timeout_secs_,
                std::move(client_id),
                nullptr,
                nullptr,
                std::move(
                   p_will_options));`

**Comment by JonathanHenson** [comment]
My impression is that passing the timeout value directly is working for you. Is this the case?

If so, how were you setting the ConfigCommon::mqtt_command_timeout value?

**Comment by certabitmh** [comment]
NO it doesn’t work. In only changed it by hand to see if lower timeouts (2 instead of 20sec) show any impact on behavior.

As stated, it takes way longer than 2 seconds until connect returns. About factor 10-20 I would say.

So That’s why my question is how time measurement for determining timeout inside connect function  could be influenced by any environmental conditions...
It’s definitely not blocked by other stuff since it runs in separate thread.

Am 05.09.2018 um 18:43 schrieb Jonathan M. Henson <notifications@github.com<mailto:notifications@github.com>>:


My impression is that passing the timeout value directly is working for you. Is this the case?

If so, how were you setting the ConfigCommon::mqtt_command_timeout value?
