### ISSUE TITLE
pthread.h not found

### ISSUE THREAD

**Issue by jbarrena** [aws/aws-iot-device-sdk-cpp#119]
Hi,

I am trying to compile the SDK for Windows 10 x64 using cmake & msbuild. I cloned the repository by master branch, and tryed cmake -G "Visual Studio 14 2015 Win64" ../.

The following error appeared on CMakeError.log:
CheckIncludeFile.cxx(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory.

Do we know why cmake is looking for pthread.h when I am compiling it for Windows??

Thanks for the help,

Julen.

**Comment by ColdenCullen** [comment]
Can you please paste the command line output you got when running CMake? I'm curious to see what part of that failed.

**Comment by jbarrena** [comment]
Hi,

The problem was with Git. It was not properly configured. Once I corrected the issue, everything went well. Thanks for your interest. Really appreciated.

Julen.

**Comment by jbarrena** [comment]
Hi again,

I am now trying to cross-compile the libraries for a Linux Embedded platform. I modified ToolchainFile.cmake and try to cross-compile the libraries. Similar errors appeared during compilation.

Attached the CMakeOutput.log and CMakeError.log

Any help would be really appreciatted.

Thanks and kind regards,

Julen.

[CMakeError.log](https://github.com/aws/aws-iot-device-sdk-cpp/files/2388130/CMakeError.log)

[CMakeOutput.log](https://github.com/aws/aws-iot-device-sdk-cpp/files/2388128/CMakeOutput.log)

**Comment by ColdenCullen** [comment]
```
CMakeFiles/cmTC_2dca4.dir/CheckSymbolExists.cxx.o: In function 'main':
CheckSymbolExists.cxx:(.text+0x16): undefined reference to 'pthread_create'
```
This isn't a compile error, but a link error. Did you add -lpthread to your link flags somewhere? The most common way to do this is via [`target_link_libraries`](https://cmake.org/cmake/help/v3.0/command/target_link_libraries.html).

**Comment by ColdenCullen** [comment]
Do you have a version of OpenSSL built for the platform you're targeting installed? CMake cannot find it. Try passing `-DOPENSSL_ROOT_DIR=C:/Path/To/OpenSSL/` to CMake to force it to look in the correct location.

**Comment by ColdenCullen** [comment]
CMake wants the path to the libraries, not the executables. Try using lib instead of bin.

**Comment by jbarrena** [comment]
No way to find OPENSSL package. I pass the lib directory from command line, and also modified the CMakeLists file to define the paths, but no library found. I also tried to specify the file name in OPENSSL_LIBRARIES but no change on the result?

Any ideas??
