### ISSUE TITLE
Shadow object variable

### ISSUE THREAD

**Issue by jbarrena** [aws/aws-iot-device-sdk-cpp#121]
Hi,

How can I use a Shadow variable as class global in my code? The default constructor for the shadows is deleted, so, I´m not able to declare Shadow my_shadow variable in my class.

Any help?

Thanks

**Comment by ColdenCullen** [comment]
You can declare a `Shadow` in your class if you initialize it in the initializer list in your constructor. See [this page](https://en.cppreference.com/w/cpp/language/initializer_list) for more details.
