### ISSUE TITLE
Reconnection failure

### ISSUE THREAD

**Issue by HQarroum** [aws/aws-iot-device-sdk-cpp#129]
Hi,

I am currently working with a customer having tested the reconnection logic of the `aws-iot-device-sdk-cpp`, and we've stumbled upon a few issues:

**Used Environments**

MacOS Mojave 10.14.

GNU Linux - 2.6.66.

**Network Implementation Used**

Websockets.

**Test case 1**

The `PubSub` sample is connected using a Websocket connection to AWS IoT, and we trigger a disconnection of this client at the AWS IoT level (e.g we start a new client with the same `clientId` which disconnects the first client).

The problem is that the disconnection is not advertised to the client level (at the `PubSub` sample level), and the reconnection logic does not work. Instead, when logs are activated, we see in loop the following log:

```
[ERROR] Tue Jan  6 09:14:42 1970
:64 [WebSocket Wrapper] [0x70000f625000] [WssFrameRecvCallback:L604] : SSL Read failed, The SSL connection was closed : SDK Code -407.
```

We've noticed in the code base that in the `WebSocketConnection` class at this [line](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/network/WebSocket/WebSocketConnection.cpp#L224), the `is_connected_` variable is commented out even when the Websocket layer signals a disconnection (`WSLAY_CONNECTION_CLOSE`).

Commenting out this line along with a short keep alive interval triggers the disconnection callback as well as the reconnection logic. What is the reason behind having commented out this line?

**Test case 2**

The `PubSub` client is connected to AWS IoT and we deactivate the Wi-Fi interface. The reconnection logic is triggered after a keepalive timeout, but fails due to lack of Internet connection. We then reactivate the Wi-Fi interface, the Wi-Fi connection is re-established, and we get the following error upon reconnection:

`Server Certificate Verification failed.`

This curiously however does not happen if we reactivate the Wi-Fi interface just after having deactivated it and before the reconnection logic happens. Basically, if the reconnection logic fails once, it will issue a `Server Certificate Verification failed`, if it never failed before, the reconnection will be successful. Any advice?

**Comment by lakkeri** [comment]
Confirming test case 2, you can trigger this by disabling network interface.
[This line](https://github.com/aws/aws-iot-device-sdk-cpp/blob/5bdc1dbe863ee27226ce736a6bbec55f9a995fcc/network/OpenSSL/OpenSSLConnection.cpp#L375) returns X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY if there is no network connection, and still returns same result if network connection reestablished.

**Comment by HQarroum** [comment]
Any update yet on this issue?

**Comment by jmklix** [comment]
@HQarroum sorry for the long wait, but are you still having these issues?
If you haven't already take a look at [c++ v2](https://github.com/aws/aws-iot-device-sdk-cpp-v2).
