### ISSUE TITLE
When subscribing to a topic with wildcards, callback is not called

### ISSUE THREAD

**Issue by serjiozh** [aws/aws-iot-device-sdk-cpp#13]
When an application subscribes to a topic using wildcards '+' or '#', it receives Publish messages from the server, but the function ClientState::GetSubscription cannot find the proper subscription and therefore the application handler callback is not called.

The following patch seems to resolve the issue for me:

--- src/mqtt/ClientState.cpp    22 May 2017 15:59:16 -0000      1.1.1.1
+++ src/mqtt/ClientState.cpp    26 May 2017 16:49:56 -0000
@@ -54,11 +54,43 @@
 
                std::shared_ptr<Subscription> ClientState::GetSubscription(util::String p_topic_name) {
                        std::shared_ptr<Subscription> p_sub = nullptr;
+
                        util::Map<util::String, std::shared_ptr<Subscription>>::const_iterator itr = subscription_map_.find(p_topic_name);
                        if(itr != subscription_map_.end()) {
                                p_sub = itr->second;
+                return p_sub;
                        }
 
+            //  Handle '+' or '#'
+            for (const auto &pair : subscription_map_) {
+                size_t index1, index2;
+                for (index1 = index2 = 0; index1 < p_topic_name.size() && index2 < pair.first.size(); ) {
+                    if (pair.first[index2] == '#' && index2 + 1 >= pair.first.size()) {
+                        //  Terminating '#'
+                        p_sub = pair.second;
+                        return p_sub;
+                    }
+                    if (pair.first[index2] == '+' && (index2 == 0 || pair.first[index2 - 1] == '/') && (index2 + 1 >= pair.first.size() || pair.first[index2 + 1] == '/')) {
+                        //  A '+' that replaces a whole topic
+                        index2++;
+                        while (index1 < p_topic_name.size() && p_topic_name[index1] != '/') {
+                            index1++;
+                        }
+                    } else if (p_topic_name[index1] == pair.first[index2]) {
+                        index1++;
+                        index2++;
+                    } else {
+                        //  Mismatch found
+                        break;
+                    }
+                }
+                if (index1 >= p_topic_name.size() && index2 >= pair.first.size()) {
+                    //  Match found
+                    p_sub = pair.second;
+                    return p_sub;
+
+                }
+            }
                        return p_sub;
                }

**Comment by chaurah** [comment]
Hi @serjiozh,
    Thank you for the patch. This is a known issue that we have fixed internally already and the fix will be included in the next release of the SDK. I will keep this issue open until the release is out. Please let me know if you have any further questions/suggestions.

Rahul

**Comment by chaurah** [comment]
The SDK has been updated to support wildcard based subscriptions with the v1.1 release.
Please reopen if you have any further questions.

Rahul
