### ISSUE TITLE
Possible Shadow subscriction bug

### ISSUE THREAD

**Issue by vzaychenko** [aws/aws-iot-device-sdk-cpp#146]
**Description of problem:**

Using Shadow, if we set the handler to change only (Delta) the document, our handler is never called.

During the experiments, we found that the Delta handler is called only if we also set the handler to update the document. But if we setup Update handler we'll get a traffic overhead, because automatically we got all changes of the Shadow document.

So we never can get only (Delta) of the current document.

Looking at the AWS IoT C++ SDK code, we discovered a possible implementation error. Logicaly here should be or Delta or Update. But we can see only Update process even we request to subscribe on Delta.

"Shadow.cpp" method "Shadow::HandleUpdateResponse":

```
        util::Map<ShadowRequestType, RequestHandlerPtr>::iterator request_itr
            = request_mapping_.find(ShadowRequestType::Update);
        if (request_itr != request_mapping_.end() && nullptr != request_itr->second) {

```
   
There you can find that std::equal triggered on update and update/delta as well:

$aws/things/THING_NAME/shadow/update
$aws/things/THING_NAME/shadow/update/delta

"Shadow.cpp" method "Shadow::SubscriptionHandler":

```
if (ResponseCode::SUCCESS == rc) {
    rc = ResponseCode::SHADOW_UNEXPECTED_RESPONSE_TOPIC;
    if (std::equal(shadow_topic_get_.begin(), shadow_topic_get_.end(), topic_name.begin())) {
        rc = HandleGetResponse(response_type, json_payload);
    } else if (std::equal(shadow_topic_update_.begin(), shadow_topic_update_.end(), topic_name.begin())) {
        rc = HandleUpdateResponse(response_type, json_payload);
    } else if (std::equal(shadow_topic_delete_.begin(), shadow_topic_delete_.end(), topic_name.begin())) {
        rc = HandleDeleteResponse(response_type, json_payload);
    }
}

```

**Comment by shekharhimanshu** [comment]
This might help fix your problem.
https://github.com/aws/aws-iot-device-sdk-cpp/pull/124

Sadly the PR is open for quite sometime now without any reply.

**Comment by graebm** [comment]
Thanks for the PR. It has been merged to master
