### ISSUE TITLE
Poor performance on low quality network connections

### ISSUE THREAD

**Issue by samvrlewis** [aws/aws-iot-device-sdk-cpp#147]
Background of what I'm trying to do:
- Using the AWS C++ IoT SDK to send MQTT messages to AWS IoT
- One message sent every ~10s
- Messages are, at the biggest, about 50KB
- Using QoS1

Using the AWS C++ SDK, this works really nicely if our sensor has a good and stable connection to the internet.

However, the issue is that on connections that are worse performing the SDK gets a lot of socket write errors. Trying with the Python SDK, it works nicely on the same connection when I send the same amount of data over the link at the same interval - which leads me to think that there's something about C++ SDK implementation (or the way we have configured it) that makes it not work well with flakier connections?

From what I've seen when using the C++ SDK, typically one or two messages will get through before we get an error like this:

`[1864098192] [PerformAction:L210] : Publish Write to Network Failed. Error occurred during the SSL write operation : SDK Code -408.`

Then, usually after a minute or so the SDK will reconnect to AWS IoT and then send one or two messages before erroring and repeating the process. Because of this, we are creating messages much faster than we can send them out.

On a sensor where this happens, I measured the upload throughput (to the internet) as ~200 Kbit/s, download throughput as ~400 Kbit/s, and packet loss at ~8%. This is over a WiFi connection

Have tried playing with the socket timeout times in the C++ SDK to no avail - currently using a 10s read and write timeout.

Is there any way I can make the performance better on low quality network connections?

Appreciate any help.

[Logs of a sensor with this issue.](https://github.com/aws/aws-iot-device-sdk-cpp/files/2815159/Detexy_logs_on_flakey_connection.txt)

**Comment by JonathanHenson** [comment]
Have you tried v2? It’s specifically designed to address many of these issues.

github.com/awslabs/aws-iot-device-sdk-cpp-v2

**Comment by JonathanHenson** [comment]
V2 is already more production ready than this library ever was. Granted it’s not officially GA, but if you used this one, you’ve got nothing to lose. 

There’s a v2 for python as well, and the PYPI packages will be published within the week. It runs on the same codebase the c++ version does.
