### ISSUE TITLE
How to use this sdk on arduino ide

### ISSUE THREAD

**Issue by ngoc233** [aws/aws-iot-device-sdk-cpp#150]
Hello ,  I'm using arduino ide to code for esp8266. But I cannot use this sdk on arduino ide . I  copied  "aws-iot-device-sdk-cpp" to project folder and  _#include "aws-iot-device-sdk-cpp/samples/PubSub/PubSub.hpp"_ but unsuccessful. I'm thinking , this is not right solution so Does anyone have an solution?

**Comment by JonathanHenson** [comment]
I doubt you'll be able to build this on arduino. 

Do you have build output? We'll need info on the environment to be of more assistance.

You likely want the C SDK.

**Comment by ngoc233** [comment]
Maybe I went wrong. I used this like library . I'm thinking for using it I need to porting this SDK to my firmware , right? I'm using esp8266 on arduino ide.

**Comment by ngoc233** [comment]
I read a same issue in  C SDK. Seem AWS iot  doesn't support for esp8266

**Comment by hjiawei** [comment]
I think you need to use [ESP8266_RTOS_SDK](https://github.com/espressif/ESP8266_RTOS_SDK) if you are still looking for solutions. It has [aws_iot](https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/components/aws_iot) component (the AWS IoT Embedded C SDK) already included as part of the SDK. It is not as easy as the Arduino IDE but not too difficult either.
