### ISSUE TITLE
unable to make on windows 10

### ISSUE THREAD

**Issue by myamma** [aws/aws-iot-device-sdk-cpp#154]
Hi, 

I am using windows 10, visual studio 2017 and git bash. 
I followed the installation guide of this repo and was able to use cmake to build the makefile. However, when i use the command "make -f aws-iot-sdk-cpp.sln", i got error "aws-iot-sdk-cpp.sln:1: *** missing separator.  Stop." After some googling, the issue appears to be related to space vs. tab usage inside makefile? 
i am new to makefile and build process in general. I have attached the makefile [in txt format since github does not allow sln format]. 
Would anyone more experienced be able to shed some light on:
1. Is the make error related to space vs tab usage in makefile?
2. If so, what part of makefile should i change? and how should i modify it?

Thanks a lot!
[aws-iot-sdk-cpp.txt](https://github.com/aws/aws-iot-device-sdk-cpp/files/3190185/aws-iot-sdk-cpp.txt)

**Comment by bretambrose** [comment]
If you successfully ran cmake to generate solution files, you should be able to load and build the solutions in Visual Studio.
