### ISSUE TITLE
CMAKE Failed

### ISSUE THREAD

**Issue by agilesai1294** [aws/aws-iot-device-sdk-cpp#156]
![Capture_AWS](https://user-images.githubusercontent.com/34946584/58642258-f9f37f00-82ca-11e9-96a4-144f5d97d82a.PNG)

**Comment by David-Haim** [comment]
Same.
(BTW, the v2 build process of the aws-iot is also broken)

**Comment by ColdenCullen** [comment]
Hey, the tests require that libcurl be installed. If you have in installed in a non-standard location, try passing `-DCMAKE_PREFIX_PATH` to point it in the right direction. If you choose not to install libcurl, you can skip building the tests by passing `-DBUILD_TESTS=OFF`.
