### ISSUE TITLE
Can this SDK works with C++0x?

### ISSUE THREAD

**Issue by agilesai1294** [aws/aws-iot-device-sdk-cpp#159]
I am trying to port this SDK on to one of the legacy devices which use c++0x standard. I was able to build the project and when i tried to make it i get the following error.

[  1%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/Action.cpp.obj
In file included from /home/bharathaws/aws-iot-device-sdk-cpp/src/Action.cpp:26:
/home/bharathaws/aws-iot-device-sdk-cpp/include/Action.hpp:30: fatal error: atomic: No such file or directory
compilation terminated.
CMakeFiles/aws-iot-sdk-cpp.dir/build.make:62: recipe for target 'CMakeFiles/aws-iot-sdk-cpp.dir/src/Action.cpp.obj' failed
make[2]: *** [CMakeFiles/aws-iot-sdk-cpp.dir/src/Action.cpp.obj] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/aws-iot-sdk-cpp.dir/all' failed
make[1]: *** [CMakeFiles/aws-iot-sdk-cpp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by justinboswell** [comment]
Unfortunately, this SDK requires/depends on C++11 features, as detailed [here](https://github.com/aws/aws-iot-device-sdk-cpp#installation).
