### ISSUE TITLE
Preempting IoT Connection Actions for Shutdown

### ISSUE THREAD

**Issue by kmiller15211** [aws/aws-iot-device-sdk-cpp#160]
**Background**
Hello, we are using the IoT C++ SDK latest released version and I had a question about shutdown/object destruction. We are using the IoT SDK and the provided OpenSSLConnection object. We are using it in async mode, so that publish and subscribe both make the request and then watch for a system shutdown signal or a confirmation that the call succeeded. We are running the code that communicates to AWS IoT in a separate thread from the main thread that will ultimately be the one trying to shut down the system - it must signal a shutdown through an asynchronous event, and then our AWS IoT thread must see that, and cleanly exit. 

We are using the C++ SDK on an Embedded Linux mobile device, and we have no power button - only a small cap to keep the processor alive while we shutdown. This means that our code must react to the shutdown almost immediately and terminate as fast as possible. 

This causes several issues: 
1.) We know that connect is blocking and must take the appropriate timeout seconds to give up, which is a problem if we're in the midst of a connect when the system begins to shutdown - it takes too long. 
2.) If we are in the midst of a publish async call and waiting, it seems like the disconnect call takes the KeepAliveTimeout to complete - also longer than we can accept. 

**Summary**
Does anyone have tips for using the SDK API calls such that we can interrupt any of them if we get the signal to shut down? For instance, if we're in the middle of a connect/publish/subscribe and we need to stop any of these actions to shut down and destroy the object, is it even possible?

**Comment by bretambrose** [comment]
If your primary concern is just achieving a responsive shutdown (despite having to use a potentially long-blocking API in the background), is detaching your network thread an option?

**Comment by kmiller15211** [comment]
Thank you for the idea & response.

The problem is that the networking thread is using resources that I am
going to destruct. I could pass smart pointers into it to allow it to keep
the objects alive, but once you start doing that, there’s often a chain
reaction due to those objects needing more objects (network driver and
power stuff) & more complexity.

**Comment by bretambrose** [comment]
Another possibility you may want to look into is the v2 SDK: https://github.com/awslabs/aws-iot-device-sdk-cpp-v2

While still in public preview, its asynchronous API does not contain any blocking IO and should support fast shutdown.
