### ISSUE TITLE
Unable to consume AWS STS credentials generated by Lambda for connecting to IoT Core endpoint.

### ISSUE THREAD

**Issue by jaikeshsinghgithub** [aws/aws-iot-device-sdk-cpp#164]
I am unable to connect to AWS IoT endpoint, using STS credentials (AssumeRoleUsingWebIdentity) generated by AWS Lambda.

It is throwing me AMQJS0008I Socket closed error

I tried connecting to the same endpoint with the STS credentials (AssumeRoleUsingWebIdentity) and roles generated via AWS CLI & it worked.

But, not sure why this is not working with Lambda.

My Architectural Diagram is 

![Untitled](https://user-images.githubusercontent.com/31641221/62058157-9213d300-b23e-11e9-83af-6fb54a5b6d16.png)

My Code is 

const params = {
        DurationSeconds: 43000, 
        RoleArn: 'arn:aws:iam::123456789123:role/TestRole',
        RoleSessionName: "IoT-User", 
        WebIdentityToken: "<token>",
        Policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"Stmt1\",\"Effect\":\"Allow\",\"Action\":\"s3:ListAllMyBuckets\",\"Resource\":\"*\"}]}"
    };

    const data = await sts.assumeRoleWithWebIdentity(params).promise();

![asdasd](https://user-images.githubusercontent.com/31641221/62058259-c7202580-b23e-11e9-8ecb-d34bd0e6ecf2.png)

**Comment by justinboswell** [comment]
The policy above only includes s3:ListAllMyBuckets. From the docs on [```AssumeRoleUsingWebIdentity```](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html): 
> "The resulting session's permissions are the intersection of the role's identity-based policy and the session policies." 

Therefore, even if the assumed role has IoT permissions, the final credentials will not due to the specified inline policy.

**Comment by jaikeshsinghgithub** [comment]
Thanks  justinboswell
