### ISSUE TITLE
How to create 50+ topics in aws iot core scalability side 

### ISSUE THREAD

**Issue by jaikeshsinghgithub** [aws/aws-iot-device-sdk-cpp#165]
We are doing publisher subscriber use case using IOT CORE Topics , but AWS IoT Limits showing only 50 topics can create maximum , My question is how i deal with more then 50 topics , in my project more then 200 topics subscribe by single user but AWS IoT limit is only 50 topics .

Please look https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot

Please help me how we achieve solution to overcome more then 50 topics

**Comment by graebm** [comment]
MQTT supports the use of wildcards in the subscription topic. A subscription that uses wildcards only counts as 1 subscription against your limits, even though it may grant access to any number of topics.

There are two types of MQTT wildcards:
1) `+` is a single level wildcard
2) `#` is a multi-level wildcard

See the docs for more info: https://docs.aws.amazon.com/iot/latest/developerguide/topics.html

**Comment by jaikeshsinghgithub** [comment]
Thanks graebm , let me try
