### ISSUE TITLE
Security concern for reading key files from local folder

### ISSUE THREAD

**Issue by randxie** [aws/aws-iot-device-sdk-cpp#166]
When initializing iot device connection to AWS IoT, device_certificate_relative_path and device_private_key_relative_path are assumed to stored in a local folder. It raises security concern if some one is able to access the system and steal these key files. 

Is there a way to embed these key files during build time so that the credentials are hidden inside the binary? At lease, if you can provide a way to pass device_certificate_string and device_private_key_string instead of relative paths, it will greatly help reducing the security concern.

**Comment by bretambrose** [comment]
From a security posture, if someone has access to your cert files then they most likely have access to your binary.  You're not any more protected by embedding the cert.

Being able to read the cert from memory would be a useful feature (as a bridge to pkcs11 support for example).  The being said, this SDK is currently in maintenance mode (no new features planned) as we get ready to GA the v2 SDK (which can be found [here](https://github.com/awslabs/aws-iot-device-sdk-cpp-v2)).

**Comment by randxie** [comment]
Thanks for the quick response. Yeah, be able to read cert from memory would be super helpful! Look forward to see the GA v2 sdk.
