### ISSUE TITLE
When is the disconnect callback called?

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#17]
Hello,

Thank you for adding the disconnect callback in v1.1.0. Could you please explain when will applications receive this callback?

**Comment by vareddy** [comment]
Hi @shekharhimanshu,
The disconnect callback will be called when the keep-alive ping request fails, which means that the device has been disconnected, and just before it starts the auto-reconnect procedure. 
The relevant code can be found [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Connect.cpp#L389)
I have provided more details in the other question that you posted (#18)
Please let us know if you have any more questions.
Thanks!
Varun

**Comment by shekharhimanshu** [comment]
Hello @vareddy

Thank you for those details.
It looks like the disconnect callback will not be called if auto-enabled is false. See [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Connect.cpp#L382). Is this by design?

When auto-reconnect is set to false, the client will disconnect after keep-alive period. Does that mean applications won't receive any notification about that disconnect event?

**Comment by vareddy** [comment]
Hi @shekharhimanshu,
The disconnect callback should be called even when the auto-reconnect is set to false. We seem to have missed this situation in our testing. I have made the fix in our internal repository and will be included in the next release. 
Thanks a lot for your inputs! They are very useful for improving the SDK. 
Varun

**Comment by shekharhimanshu** [comment]
Looking forward to the next release.
Thanks.

**Comment by vareddy** [comment]
Hi @shekharhimanshu,
v1.1.1 of the SDK addresses this and ensures that the disconnect callback is called even when auto-reconnect is disabled. Please let us know if you see any more issues.
Thanks!
Varun
