### ISSUE TITLE
Failing Cross compilation with openssl & curl error for aarch64-linux-gnu

### ISSUE THREAD

**Issue by viren-moradiya** [aws/aws-iot-device-sdk-cpp#173]
Hello Everyone,

I am doing cross compilation of aws-iot-device-sdk-cpp using aarch64-linux-gnu tool-chain.
I am doing this task on Ubuntu 18.04.

I have export the tool-chain path and cross compiled the openssl package with tool chain.
However, **cmake** command is getting run successfully, but while running **make** command I am facing error with **fatal error: curl/curl.h: No such file or directory** as well as **-Werror=deprecated-declarations for openssl**.
Please find my complete log as below:

$ **cmake ../aws-iot-device-sdk-cpp/ -DOPENSSL_ROOT_DIR=/home/mcbin/openssl/install/ -DCURL_INCLUDE_DIR=/home/einfochips/Growhouse/curl/install/include -DCURL_LIBRARY=/home/einfochips/Growhouse/curl/install/lib/libcurl.so**

-- The CXX compiler identification is GNU 7.4.1
-- Check for working CXX compiler: /home/einfochips/Growhouse/gcc-linaro-7.4.1-2019.02-i686_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++
-- Check for working CXX compiler: /home/einfochips/Growhouse/gcc-linaro-7.4.1-2019.02-i686_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/einfochips/Growhouse/device_sdk_build/third_party/rapidjson/download
Scanning dependencies of target rapidjson
[ 11%] Creating directories for 'rapidjson'
[ 22%] Performing download step for 'rapidjson'
Cloning into '.'...
[ 33%] No patch step for 'rapidjson'
[ 44%] No update step for 'rapidjson'
[ 55%] No configure step for 'rapidjson'
[ 66%] No build step for 'rapidjson'
[ 77%] No install step for 'rapidjson'
[ 88%] No test step for 'rapidjson'
[100%] Completed 'rapidjson'
[100%] Built target rapidjson
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found OpenSSL: /home/mcbin/openssl/install/lib/libcrypto.so  
-- Found CURL: /home/einfochips/Growhouse/curl/install/lib/libcurl.so (found version "7.68.0-DEV") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/einfochips/Growhouse/device_sdk_build/third_party/googletest/download
Scanning dependencies of target googletest
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'src'...
Already on 'master'
Your branch is up to date with 'origin/master'.
[ 33%] No patch step for 'googletest'
[ 44%] Performing update step for 'googletest'
Current branch master is up to date.
[ 55%] No configure step for 'googletest'
[ 66%] No build step for 'googletest'
[ 77%] No install step for 'googletest'
[ 88%] No test step for 'googletest'
[100%] Completed 'googletest'
[100%] Built target googletest
-- The C compiler identification is GNU 7.4.1
-- Check for working C compiler: /home/einfochips/Growhouse/gcc-linaro-7.4.1-2019.02-i686_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
-- Check for working C compiler: /home/einfochips/Growhouse/gcc-linaro-7.4.1-2019.02-i686_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- The following features have been enabled:

 * Cli, the command line interface
 * Samples, example programs making use of the SDK
 * Tests, unit and integration tests

-- The following OPTIONAL packages have been found:

 * PythonInterp

-- The following REQUIRED packages have been found:

 * CURL
 * Threads
 * OpenSSL

-- The following features have been disabled:

 * SharedLibrary, build the library as shared objects
 * Docs, HTML based API documentation

-- Configuring done
-- Generating done
-- Build files have been written to: /home/einfochips/Growhouse/device_sdk_build

$ make -j4
[  1%] Building CXX object third_party/googletest/build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  3%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/Action.cpp.o
[  3%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/ClientCoreState.cpp.o
[  4%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/ClientCore.cpp.o
[  6%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/NetworkConnection.cpp.o
[  7%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/ResponseCode.cpp.o
[  8%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/discovery/Discovery.cpp.o
[  9%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/discovery/DiscoveryResponse.cpp.o
[ 10%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/jobs/Jobs.cpp.o
[ 12%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/mqtt/Client.cpp.o
[ 13%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/mqtt/ClientState.cpp.o
[ 14%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/mqtt/Common.cpp.o
[ 15%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/mqtt/Connect.cpp.o
[ 16%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/mqtt/GreengrassMqttClient.cpp.o
[ 18%] Linking CXX static library ../../../../lib/libgtest.a
[ 18%] Built target gtest
[ 19%] Building CXX object third_party/googletest/build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 20%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/mqtt/NetworkRead.cpp.o
[ 21%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/mqtt/Packet.cpp.o
[ 22%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/mqtt/Publish.cpp.o
[ 24%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/mqtt/Subscribe.cpp.o
[ 25%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/shadow/Shadow.cpp.o
[ 26%] Linking CXX static library ../../../../lib/libgmock.a
[ 26%] Built target gmock
[ 27%] Building CXX object third_party/googletest/build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 28%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/util/JsonParser.cpp.o
[ 30%] Linking CXX static library ../../../../lib/libgtest_main.a
[ 30%] Built target gtest_main
Scanning dependencies of target gmock_main
[ 31%] Building CXX object third_party/googletest/build/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 32%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/util/Utf8String.cpp.o
[ 33%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/util/logging/ConsoleLogSystem.cpp.o
[ 34%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/util/logging/FormattedLogSystem.cpp.o
[ 36%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/util/logging/LogLevel.cpp.o
[ 37%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/util/logging/Logging.cpp.o
[ 38%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/util/threading/ThreadTask.cpp.o
[ 39%] Linking CXX static library ../../../../lib/libgmock_main.a
[ 39%] Built target gmock_main
[ 40%] Linking CXX static library archive/libaws-iot-sdk-cpp.a
[ 40%] Built target aws-iot-sdk-cpp
Scanning dependencies of target aws-iot-unit-tests
[ 42%] Building CXX object samples/PubSub/CMakeFiles/pub-sub-sample.dir/PubSub.cpp.o
[ 43%] Building CXX object cli/CMakeFiles/aws-iot.dir/cli.cpp.o
[ 44%] Building CXX object tests/integration/CMakeFiles/aws-iot-integration-tests.dir/__/__/common/ConfigCommon.cpp.o
[ 45%] Building CXX object tests/unit/CMakeFiles/aws-iot-unit-tests.dir/__/__/samples/JobsAgent/JobsAgentOperations.cpp.o
In file included from /home/einfochips/Growhouse/aws-iot-device-sdk-cpp/samples/JobsAgent/JobsAgentOperations.cpp:34:0:
/home/einfochips/Growhouse/aws-iot-device-sdk-cpp/samples/JobsAgent/JobsAgent.hpp:28:10: **fatal error: curl/curl.h: No such file or directory**
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
tests/unit/CMakeFiles/aws-iot-unit-tests.dir/build.make:62: recipe for target 'tests/unit/CMakeFiles/aws-iot-unit-tests.dir/__/__/samples/JobsAgent/JobsAgentOperations.cpp.o' failed
make[2]: *** [tests/unit/CMakeFiles/aws-iot-unit-tests.dir/__/__/samples/JobsAgent/JobsAgentOperations.cpp.o] Error 1
CMakeFiles/Makefile2:238: recipe for target 'tests/unit/CMakeFiles/aws-iot-unit-tests.dir/all' failed
make[1]: *** [tests/unit/CMakeFiles/aws-iot-unit-tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 46%] Building CXX object tests/integration/CMakeFiles/aws-iot-integration-tests.dir/src/AutoReconnect.cpp.o
[ 48%] Building CXX object tests/integration/CMakeFiles/aws-iot-integration-tests.dir/src/IntegTestRunner.cpp.o
[ 49%] Building CXX object cli/CMakeFiles/aws-iot.dir/__/common/ConfigCommon.cpp.o
[ 50%] Building CXX object tests/integration/CMakeFiles/aws-iot-integration-tests.dir/src/JobsTest.cpp.o
[ 51%] Building CXX object tests/integration/CMakeFiles/aws-iot-integration-tests.dir/src/MultipleClients.cpp.o
[ 53%] Building CXX object cli/CMakeFiles/aws-iot.dir/__/network/OpenSSL/OpenSSLConnection.cpp.o
[ 54%] Building CXX object samples/PubSub/CMakeFiles/pub-sub-sample.dir/__/__/common/ConfigCommon.cpp.o
/home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp: In member function ‘awsiotsdk::ResponseCode awsiotsdk::network::OpenSSLConnection::LoadCerts()’:
**/home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp:364:95: error: ‘int SSL_CTX_load_verify_locations(SSL_CTX*, const char*, const char*)’ is deprecated [-Werror=deprecated-declarations]**
             if (!SSL_CTX_load_verify_locations(p_ssl_context_, root_ca_location_.c_str(), NULL)) {
                                                                                               ^
In file included from /home/mcbin/openssl/install/include/openssl/opensslv.h:109:0,
                 from /home/mcbin/openssl/install/include/openssl/macros.h:11,
                 from /home/mcbin/openssl/install/include/openssl/opensslconf.h:126,
                 from /home/mcbin/openssl/install/include/openssl/macros.h:10,
                 from /home/mcbin/openssl/install/include/openssl/ssl.h:16,
                 from /home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.hpp:40,
                 from /home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp:25:
/home/mcbin/openssl/install/include/openssl/ssl.h:2023:29: note: declared here
 DEPRECATEDIN_3_0(__owur int SSL_CTX_load_verify_locations(SSL_CTX *ctx,
                             ^
/home/mcbin/openssl/install/include/openssl/macros.h:34:38: note: in definition of macro ‘DECLARE_DEPRECATED’
 #    define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
                                      ^
/home/mcbin/openssl/install/include/openssl/ssl.h:2023:1: note: in expansion of macro ‘DEPRECATEDIN_3_0’
 DEPRECATEDIN_3_0(__owur int SSL_CTX_load_verify_locations(SSL_CTX *ctx,
 ^~~~~~~~~~~~~~~~
[ 55%] Building CXX object samples/PubSub/CMakeFiles/pub-sub-sample.dir/__/__/network/OpenSSL/OpenSSLConnection.cpp.o
cc1plus: all warnings being treated as errors
cli/CMakeFiles/aws-iot.dir/build.make:110: recipe for target 'cli/CMakeFiles/aws-iot.dir/__/network/OpenSSL/OpenSSLConnection.cpp.o' failed
make[2]: *** [cli/CMakeFiles/aws-iot.dir/__/network/OpenSSL/OpenSSLConnection.cpp.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'cli/CMakeFiles/aws-iot.dir/all' failed
make[1]: *** [cli/CMakeFiles/aws-iot.dir/all] Error 2
[ 56%] Building CXX object tests/integration/CMakeFiles/aws-iot-integration-tests.dir/src/MultipleSubAutoReconnect.cpp.o
[ 57%] Building CXX object tests/integration/CMakeFiles/aws-iot-integration-tests.dir/src/PubSub.cpp.o
[ 59%] Building CXX object tests/integration/CMakeFiles/aws-iot-integration-tests.dir/src/SdkTestConfig.cpp.o
/home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp: In member function ‘awsiotsdk::ResponseCode awsiotsdk::network::OpenSSLConnection::LoadCerts()’:
**/home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp:364:95: error: ‘int SSL_CTX_load_verify_locations(SSL_CTX*, const char*, const char*)’ is deprecated [-Werror=deprecated-declarations]**
             if (!SSL_CTX_load_verify_locations(p_ssl_context_, root_ca_location_.c_str(), NULL)) {
                                                                                               ^
In file included from /home/mcbin/openssl/install/include/openssl/opensslv.h:109:0,
                 from /home/mcbin/openssl/install/include/openssl/macros.h:11,
                 from /home/mcbin/openssl/install/include/openssl/opensslconf.h:126,
                 from /home/mcbin/openssl/install/include/openssl/macros.h:10,
                 from /home/mcbin/openssl/install/include/openssl/ssl.h:16,
                 from /home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.hpp:40,
                 from /home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp:25:
/home/mcbin/openssl/install/include/openssl/ssl.h:2023:29: note: declared here
 DEPRECATEDIN_3_0(__owur int SSL_CTX_load_verify_locations(SSL_CTX *ctx,
                             ^
/home/mcbin/openssl/install/include/openssl/macros.h:34:38: note: in definition of macro ‘DECLARE_DEPRECATED’
 #    define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
                                      ^
/home/mcbin/openssl/install/include/openssl/ssl.h:2023:1: note: in expansion of macro ‘DEPRECATEDIN_3_0’
 DEPRECATEDIN_3_0(__owur int SSL_CTX_load_verify_locations(SSL_CTX *ctx,
 ^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
samples/PubSub/CMakeFiles/pub-sub-sample.dir/build.make:110: recipe for target 'samples/PubSub/CMakeFiles/pub-sub-sample.dir/__/__/network/OpenSSL/OpenSSLConnection.cpp.o' failed
make[2]: *** [samples/PubSub/CMakeFiles/pub-sub-sample.dir/__/__/network/OpenSSL/OpenSSLConnection.cpp.o] Error 1
CMakeFiles/Makefile2:482: recipe for target 'samples/PubSub/CMakeFiles/pub-sub-sample.dir/all' failed
make[1]: *** [samples/PubSub/CMakeFiles/pub-sub-sample.dir/all] Error 2
[ 60%] Building CXX object tests/integration/CMakeFiles/aws-iot-integration-tests.dir/__/__/network/OpenSSL/OpenSSLConnection.cpp.o
/home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp: In member function ‘awsiotsdk::ResponseCode awsiotsdk::network::OpenSSLConnection::LoadCerts()’:
**/home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp:364:95: error: ‘int SSL_CTX_load_verify_locations(SSL_CTX*, const char*, const char*)’ is deprecated [-Werror=deprecated-declarations]**
             if (!SSL_CTX_load_verify_locations(p_ssl_context_, root_ca_location_.c_str(), NULL)) {
                                                                                               ^
In file included from /home/mcbin/openssl/install/include/openssl/opensslv.h:109:0,
                 from /home/mcbin/openssl/install/include/openssl/macros.h:11,
                 from /home/mcbin/openssl/install/include/openssl/opensslconf.h:126,
                 from /home/mcbin/openssl/install/include/openssl/macros.h:10,
                 from /home/mcbin/openssl/install/include/openssl/ssl.h:16,
                 from /home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.hpp:40,
                 from /home/einfochips/Growhouse/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp:25:
/home/mcbin/openssl/install/include/openssl/ssl.h:2023:29: note: declared here
 DEPRECATEDIN_3_0(__owur int SSL_CTX_load_verify_locations(SSL_CTX *ctx,
                             ^
/home/mcbin/openssl/install/include/openssl/macros.h:34:38: note: in definition of macro ‘DECLARE_DEPRECATED’
 #    define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
                                      ^
/home/mcbin/openssl/install/include/openssl/ssl.h:2023:1: note: in expansion of macro ‘DEPRECATEDIN_3_0’
 DEPRECATEDIN_3_0(__owur int SSL_CTX_load_verify_locations(SSL_CTX *ctx,
 ^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
tests/integration/CMakeFiles/aws-iot-integration-tests.dir/build.make:254: recipe for target 'tests/integration/CMakeFiles/aws-iot-integration-tests.dir/__/__/network/OpenSSL/OpenSSLConnection.cpp.o' failed
make[2]: *** [tests/integration/CMakeFiles/aws-iot-integration-tests.dir/__/__/network/OpenSSL/OpenSSLConnection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:177: recipe for target 'tests/integration/CMakeFiles/aws-iot-integration-tests.dir/all' failed
make[1]: *** [tests/integration/CMakeFiles/aws-iot-integration-tests.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I am not able to find root cause.
Request you to help me to resolve this things.

Thanks a lot!
Viren

**Comment by KaibaLopez** [comment]
Hi @viren-moradiya , 
So, first I'd like to ask you to try 2 things, first explicitly point curl location on your cmake arguments, and disable the warning. 
These are just what first comes to mind with this errors but, I think that your curl could be in an unexpected location and so the sdk can't find it, and as for the second one, it could be cause by you having openssl version 1.1.X, the sdk uses version 1.0.2 so some things may be deprecated by the newer version and giving you the warning, which the sdk is set to handle as an error.
Let me know if these worked for you.

**Comment by graebm** [comment]
The unit tests and the "JobsAgent" sample have a dependency on Curl. You can avoid compiling these with the following switches `-DBUILD_SAMPLES=OFF` `-DBUILD_TESTS=OFF`. 

If you are just getting started on a new project, you should really check out our new [version-2 SDK](https://github.com/aws/aws-iot-device-sdk-cpp-v2) instead. All new features and development efforts will be focused on this new SDK.
