### ISSUE TITLE
Known Issues in AWS Iot SDK C++

### ISSUE THREAD

**Issue by Preemali** [aws/aws-iot-device-sdk-cpp#174]
Hi,

I successfully made the sdk targets. But when I'm running them through Visual Studio, I get linking errors. I saw that there are some known issues in the SDK. The source has mentioned,
"Project structure in Solution Explorer needs to be updated" and "Working directory needs to be updated every time CMake solution is rebuilt to ${OutDir} for configuration to be picked up as expected".

Can someone please explain me how to achieve above?

Thank you

**Comment by KaibaLopez** [comment]
Hi @Preemali ,
you can change the working directory on visual studio under:
Open Project > Properties > Configuration Properties > Debugging.

**Comment by graebm** [comment]
Can you please post the full build output so we can see the specific linker error?

**Comment by graebm** [comment]
I'd also like to mention that we have a completely new version of the SDK. It is a complete rewrite, and it is where we will be focusing our features and stability efforts going forward:
[aws-iot-device-sdk-cpp-v2](https://github.com/aws/aws-iot-device-sdk-cpp-v2)

If you're just getting started on a new project, I would strongly advise starting with the new SDK

**Comment by Preemali** [comment]
@KaibaLopez Do I need to change it for all the projects including ALL_BUILD, ZERO_CHECK and INSTALL? I changed the working directory for all projects except above three.

**Comment by Preemali** [comment]
@graebm  I was able to correct the linking errors after adding libeay32MD.lib to additional dependencies in the project. Now there are no building errors. But I cannot run the project. It says something similar to  "ZERO_CHECK cannot start. Access is denied." 

My project requires mqtt client in the sdk. Because I have to publish and subscribe to a system via iot.  Can I still use version 2 for my project? I didn't see pub-sub sample in the v2.

**Comment by graebm** [comment]
Yes, you can still use [version 2](https://github.com/aws/aws-iot-device-sdk-cpp-v2) to publish and subscribe to any topic.
I just added pub-sub samples, try getting latest.

**Comment by Preemali** [comment]
@graebm Thanks a lot mate.
