### ISSUE TITLE
No support for binary data

### ISSUE THREAD

**Issue by awefsome** [aws/aws-iot-device-sdk-cpp#179]
seems aws-iot-device-sdk-cpp doesn't support the binary data as I could see it's using string underneath. In-order to send binary data, conversion from hex to ascii is required which in-turn will double the payload. Do you have any plans to add support for binary data in this library?

**Comment by JonathanHenson** [comment]
We don’t have plans to add anything to this library as development effort has moved to aws-iot-device-sdk-cpp-v2

It should support your use case. Please let us know if you have any issues.
