### ISSUE TITLE
rapidjson/document.h is not found 

### ISSUE THREAD

**Issue by swatinair1234** [aws/aws-iot-device-sdk-cpp#181]
Hi I am getting include error in JsonParson.hpp since i am not able to find this header file rapidjson/document.h in the line 
 #include <rapidjson/document.h> ..
I have succesfully built the libraries for the master branch in ubuntu.I adding the headers to run my code but i get errors due to dependency on this file. Kindly let me know where i can find this header file.

**Comment by bretambrose** [comment]
As a quick, but not-ideal solution, you can download, build, and install rapidjson the same way the SDK does (https://github.com/Tencent/rapidjson).  

A better solution would be to either move rapidjson to a formal pre-requisite (ala Openssl) or have the external project do a build and install of the header files.

**Comment by swatinair1234** [comment]
Ok Thanks a lot. I also get this error OpenSSLConnection.hpp" even though i have added the include path to aws-iot-device-sdk-cpp/network/OpenSSL in the include files.
fatal error: OpenSSLConnection.hpp: No such file or directory
 #include "OpenSSLConnection.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~
