### ISSUE TITLE
fatal error: OpenSSLConnection.hpp: No such file or directory

### ISSUE THREAD

**Issue by swatinair1234** [aws/aws-iot-device-sdk-cpp#182]
Hi i am working on the PubSub in samples. I havent created any separate main.cpp. I am trying to run the example in PubSub.cpp.When  I am try to build it . But its giving me errors like OpenSSLConnection.hpp is not found inspite of adding the include files.This is my task.json file
{
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
"version": "2.0.0",
"tasks": [
{
"taskName": "build",
"command": "g++",
"args": [
"-g",
"PubSub.cpp",
"libaws-iot-sdk-cpp.a"

        ],
        "problemMatcher": [
            "$gcc"
        ]
    }
]

}
Please let me know if i have to add any other static libs or so .Thanks in advance

**Comment by bretambrose** [comment]
Hello,

We highly recommend you use cmake to build the SDK; debugging config files for other build systems isn't something we can reliably help with.  That being said, your task definition does not show any include path directives, so it's just going to run "gcc PubSub.cpp" as if from the shell, which won't work.

**Comment by swatinair1234** [comment]
Hi Thanks for the response.i have included the header files in c_cpp_properties.json.Its as below.I have build the SDK using CMAkE and created the static library .

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/home/mahathi/Dev/aws-iot-device-sdk-cpp/include",
                "/home/mahathi/Dev/aws-iot-device-sdk-cpp/build/third_party/rapidjson/src/include/rapidjson",
                "/home/mahathi/Dev/aws-iot-device-sdk-cpp/include",
                "/home/mahathi/Dev/aws-iot-device-sdk-cpp/common",
                "/home/mahathi/Dev/aws-iot-device-sdk-cpp/build/third_party/rapidjson/src/include",
                "/home/mahathi/Dev/aws-iot-device-sdk-cpp/network/OpenSSL"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
