### ISSUE TITLE
"The MQTT request timed out: SDK Code -703."

### ISSUE THREAD

**Issue by HJD1996** [aws/aws-iot-device-sdk-cpp#185]
**What platform/OS are you using?**
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

**Prerequisite**
SetAutoReconnectEnabled(true);

**Error Message**
The application  MQTT connection is normal and reconnection mechanism is valid. When publish, it will sometimes prompt "Publish runner failed. The MQTT request timed out: SDK code-703.". And then disconnects, and when it reconnects again, the connection succeeds, and the publish is normal again.
![image](https://user-images.githubusercontent.com/33686358/81285976-efbd3180-9092-11ea-9b59-2d4a25bd72ed.png)

**Comment by jmklix** [comment]
Sorry for the slow response. Does this happen randomly or is it repeatable? also can you include a minimum code sample that reproduces this error?
