### ISSUE TITLE
Multi instance support - clarification needed

### ISSUE THREAD

**Issue by sakthisg** [aws/aws-iot-device-sdk-cpp#186]
HI,
i have specific requirement that i need to run two instances of IOT for the supporting two different region with this SDK.
For example i need to support for EU and AU. Is the multi instance Support present?
Thanks in advance for your info!

**Comment by KaibaLopez** [comment]
Hey @sakthisg ,
not really sure what you mean here...I'm kind of guessing that you want the same thing to be on 2 regions at once? In which case no, a device is set on a region. 
If that is not the question please be a bit more specific on what is you're trying to do and what is the expected behavior?

**Comment by sakthisg** [comment]
With this IOT SDK,Say i have two applications A and B - A is for region EU
and B is for region LT. Will the thing present in both the region? Will the
IOT registeration done for both the regions?

**Comment by sakthisg** [comment]
i am getting errors when i try to setup IOT. Network is working fine(Youtube and other application works). What is the reason for getting timed out?
The MQTT request timed out : SDK Code -703. waitInSecs: 60
Exiting Thread MQTT Keep alive Action!!
Successfully Exited Thread MQTT Keep alive Action!!
Exiting Thread TLS Read Action Runner!!
Successfully Exited Thread TLS Read Action Runner!!
Exiting Thread Outbound Action Processing!!
Successfully Exited Thread Outbound Action Processing!!

**Comment by sakthisg** [comment]
The issues are related to time zone hence closing this.
