### ISSUE TITLE
Clarification Needed on Disconnect 

### ISSUE THREAD

**Issue by sakthisg** [aws/aws-iot-device-sdk-cpp#192]
hi 
I am exploring the option of disconnecting and connecting the IOT based on the usage.
Consider a scenario, where the device is not used for  many days,  i don't want the device to connect to IOT Core every time the device boots up.  Shall i forcibly Disconnect MQTT Client  which is  TLS/OpenSSL based.? 
-> In this case, will the client get Reconnect call back or not which has been subscribed during the connect ? 
-->is there any issue if i do multiple time connect and disconnect based on the usage of IOT Core?

**Comment by jmklix** [comment]
First of all it is highly recommended that you use the [v2 sdk](https://github.com/aws/aws-iot-device-sdk-cpp-v2)

How do you plan on forcibly disconnecting? The sdk will keep trying to reconnect with exponential back-off until it hits the SetMaxReconnectBackoffTimeout of 128 seconds. This can be changed, and the sdk will keep trying to connect at this interval. There shouldn't be any problems with doing this multiple times.

If you haven't already take a look at the [Dev Guide](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/DevGuide.md).
