### ISSUE TITLE
Secure Tunneling

### ISSUE THREAD

**Issue by rangi-vivek** [aws/aws-iot-device-sdk-cpp#193]
I have compiled Secure Tunneling sample application. But when i am running the application using the command: ./tunnel-notification --endpoint <my-end-point> --cert <My_cert_pem.crt> --key <my_private_key.pem.key> --ca_file <my_ca_file> --thing_name <my_thing_name> , I am getting following error:
AWS libcrypto resolve: searching process and loaded modules
AWS libcrypto resolve: found static aws-lc HMAC symbols
AWS libcrypto resolve: found static aws-lc libcrypto 1.1.1 EVP_MD symbols
Connecting...
Connection completed with return code 0
############################################################################################notification
topic =
topic = $aws/things/secure-tunnel-demo/tunnels/notify
MQTT Connection failed with error 5138 : 2

Can anyone tell why I am getting the Connection failed error with compiled "tunnel-notification" application. I have also followed the link https://github.com/aws-samples/iot-secure-tunneling-demo/blob/master/docs/prereqs.md to configure the AWS Clpoud 9 environment. Kindly help

**Comment by jmklix** [comment]
It looks like you are trying to use the [v2 sdk](https://github.com/aws/aws-iot-device-sdk-cpp-v2). Can you open an issue there?
