### ISSUE TITLE
No information about aws-iot-device-sdk-cpp library in AWS IoT documentation

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#2]
Hello,

I am planning to use AWS IoT PubSub functions for one of my projects and needed client SDK for the same. [AWS Developer guide](http://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html) mentions about [aws-iot-device-sdk-embedded-C](https://github.com/aws/aws-iot-device-sdk-embedded-C) but I could not find any documentation for this SDK.

If possible, I would like to use cpp sdk in our production code instead of the embedded c one, but lack of mention about this sdk in any official AWS documentations makes me wonder if this sdk is intended to be used for production yet.

Could you please clarify this?

**Comment by chaurah** [comment]
Hi @shekharhimanshu,
       You are correct about the documentation issue. We seem to have missed out on updating all of the documentation pages where SDKs are mentioned. You can see on [this](https://aws.amazon.com/iot/sdk/) page for example, that the C+ SDK is indeed mentioned. I will add an internal task for our team to ensure documentation has been updated properly in all AWS docs pages. Please let me know if you find any other similar issues.

Thank you for using AWS IoT.

Rahul

**Comment by shekharhimanshu** [comment]
Hello @chaurah,

Thanks for the clarification. Yes, i seemed to have missed the [AWS IoT Device SDK](https://aws.amazon.com/iot/sdk/) link and it does indeed mention about the C++ SDK.

I have one more query about the next milestone for this SDK (preferably resolving some of the known issues in the last release). Any ETA on that?

**Comment by chaurah** [comment]
Hi @shekharhimanshu,
       Unfortunately we cannot give out any specific timelines for our releases. We are already working on the SDK for the next release. Do you have any specific known issue that you would like us to prioritize? Any other additional features you would like to see? Your feedback would be extremely helpful.

Rahul

**Comment by shekharhimanshu** [comment]
Hello @chaurah,

Okay. I understand that.
I have opened separate issue since that was not related to this one here, #4.
Please have a look at it. I will close this issue now.

Cheers!
