### ISSUE TITLE
SSL_CTX_new() | Segmentation fault

### ISSUE THREAD

**Issue by Sourabh-ALTEN** [aws/aws-iot-device-sdk-cpp#200]
### Describe the bug

Hello All,

We are currently using AWS IoT SDK-CPP v1 to build our application. But recently we are facing segmentation fault in the `/network/OpenSSL/OpenSSLConnection.cpp` when running the sdk. Its throwing error for 

```
if ((p_ssl_context_ = SSL_CTX_new(method)) == NULL) {
                AWS_LOG_ERROR(OPENSSL_WRAPPER_LOG_TAG, " SSL INIT Failed - Unable to create SSL Context");
                return ResponseCode::NETWORK_SSL_INIT_ERROR;
            }
```
And the error message is:

```
if ((p_ssl_context_ = SSL_CTX_new(method)) == NULL) {
Program
  received signal SIGSEGV, Segmentation fault.
```

The `method` used is `TLS_method()`. We didn't made any changes to this section and it was running fine previously. 

Can anyone please let me know what could be the issue and how to resolve it?

P.S: please let me knopw if further info is needed. Currently, switching to newer SDK is not an option for us.

### Expected Behavior

No error message from OpenSSL

### Current Behavior

Segmentation fault in /network/OpenSSL/OpenSSLConnection.cpp

### Reproduction Steps

-

### SDK version used

v1

### Environment details (OS name and version, etc.)

Running SDK in VS Code with WSL connection to Docker container

**Comment by jmklix** [comment]
Which branch of this sdk are you using: `Main` or `locking-fixes`? The `locking-fixes` branch has a few fixes that might prevent the seg fault that you're seeing.

**Comment by Sourabh-ALTEN** [comment]
Hello @jmklix I am currently using `Master` default branch.

**Comment by jmklix** [comment]
Can you try using the `locking-fixes` branch?
