### ISSUE TITLE
OpenSSL wrapper is stuck and leading to connection time out

### ISSUE THREAD

**Issue by Sourabh-ALTEN** [aws/aws-iot-device-sdk-cpp#201]
### Describe the bug

I have an application developed using aws-iot sdk and it was working fine earlier. Now while connecting to aws the OpenSSL wrapper is stuck at [ConnectTCPSocket:L271](https://github.com/aws/aws-iot-device-sdk-cpp/blob/4a9b2da6003ee753a5da533f333f4675ea8d87b7/network/OpenSSL/OpenSSLConnection.cpp#L271) But it says it could resolve the endpoint and after sometime it time outs. There was a similar issue [https://github.com/aws/aws-iot-device-sdk-cpp/issues/5](url) but in my case network is available. Device is connected to network and also ping to aws endpoint is working. 

Can anyone please let me know what could be the issue here and how to resolve it?

### Expected Behavior

Successful connection to aws backend

### Current Behavior

OpenSSL wrapper is stuck at [ConnectTCPSocket:L271](https://github.com/aws/aws-iot-device-sdk-cpp/blob/4a9b2da6003ee753a5da533f333f4675ea8d87b7/network/OpenSSL/OpenSSLConnection.cpp#L271)

### Reproduction Steps

.

### SDK version used

v1

### Environment details (OS name and version, etc.)

Client application is running on Linux based embedded platform

**Comment by jmklix** [comment]
Which version of OpenSSL are you using? How often does this happen? Is it possible that your device is temporarily loosing connection?

**Comment by Sourabh-ALTEN** [comment]
Hello @jmklix , OpenSSL version on device is 1.1.1k. This is happening for the first time. I have tried with multiple network connections but it's the same situation. Is there any way I could check if this is related to dns resolving and network problem?

**Comment by jmklix** [comment]
Enabling the logs might let us figure out what is happening. You can do that with the [following](https://github.com/aws/aws-iot-device-sdk-cpp/blob/b9f3b37a1ead7965b8219d19ab7acd4e40a36a4c/README.md#logging):
```cpp
std::shared_ptr<awsiotsdk::util::Logging::ConsoleLogSystem> p_log_system =
    std::make_shared<awsiotsdk::util::Logging::ConsoleLogSystem>(awsiotsdk::util::Logging::LogLevel::Info);
awsiotsdk::util::Logging::InitializeAWSLogging(p_log_system);
```

**Comment by Sourabh-ALTEN** [comment]
Hello @jmklix logging is already enabled and the above code is already part of `main()`
