### ISSUE TITLE
MQTT publish subscribe example without TLS.

### ISSUE THREAD

**Issue by karthikkumarb** [aws/aws-iot-device-sdk-cpp#209]
### Describe the feature

Hi, I am looking for a pub/sub example without a TLS feature, Like the plaintext example we have in aws-iot-C sdk. 

### Use Case

This will be helpful to connect to other brokers also like Mosquittto without TLS.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

1.11.136

### Environment details (OS name and version, etc.)

Linux

**Comment by jmklix** [comment]
Sorry, but this sdk is no longer accepting any feature requests. Please check out our v2 sdk [samples](https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/main/samples). I don't think we have the sample you are looking for, but you can make a feature request on that repo.
