### ISSUE TITLE
Feature request: Reconnect and resubscribe callback

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#21]
Hello,

It would be nice if SDK notifies about reconnect and resubscribe events to applications when the Keep-Alive runner thread reconnects and resubscribes.

Thanks.

**Comment by vareddy** [comment]
Hi @shekharhimanshu,
This is a good feature to have and I've created a task in our backlog to add it into the SDK. 
Please let us know if there are more features you would like included into the SDK.
Thanks!
Varun

**Comment by vareddy** [comment]
The feature has been pushed to master.
