### ISSUE TITLE
Clarification regarding "Utf8cpp" third party license

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#22]
Hello,

According to [NOTICE](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/NOTICE) file [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/NOTICE#L15), the SDK depends on some `Utf8cpp` library.

Could you please clarify the following things about this `Utf8cpp` library?
- Where is this library used inside the SDK.
- `Utf8cpp` library GitHub? link
- `Utf8cpp` library version used
- `Utf8cpp` library license link

Thanks

**Comment by chaurah** [comment]
Hi @shekharhimanshu,
     Here's the information you requested:
# URL of the download site - https://github.com/nemtrif/utfcpp 
# License type and location - License is included in each .h file in the code. For example: https://github.com/nemtrif/utfcpp/blob/master/source/utf8.h 
# What the open source package does - This library implements a utf8 string class for c++. We are only using the validation functions located in : https://github.com/nemtrif/utfcpp/blob/master/source/utf8/core.h
# Locations where dependency is added in code - https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/util/Utf8String.cpp#L28

One thing to note, this implementation doesn't come with corresponding unit tests within the SDK at the moment. I have been working on them internally and will be including them with the next release.
Please let me know if you have further questions.

Rahul

**Comment by shekharhimanshu** [comment]
Thank you for the clarification.
Could you also tell me the library version used at the moment inside the SDK?
https://github.com/nemtrif/utfcpp/releases

**Comment by chaurah** [comment]
It should be v2.3.4. I will be updating this to the latest version in the next release though.
I will make a note of the currently used version in the LICENSES file as well as the NOTICE file.

Rahul
