### ISSUE TITLE
Where can I get the Greengrass core SDK?

### ISSUE THREAD

**Issue by zhy989** [aws/aws-iot-device-sdk-cpp#30]
Does the core SDK open to us ?

**Comment by vareddy** [comment]
Hi @zhy989,
By core SDK do you mean the AWS Greengrass SDK, used for deploying Lambda functions written in python 2.7 to the Greengrass Core or the  source code for the actual Greengrass Core?
The AWS Greengrass SDK can be downloaded after logging into the AWS Console. More information can be found on the [Greengrass FAQs page](https://aws.amazon.com/greengrass/faqs/).
Please let us know if you have any more questions.
Thanks!
Varun
