### ISSUE TITLE
issue about compile the source code

### ISSUE THREAD

**Issue by zhy989** [aws/aws-iot-device-sdk-cpp#31]
when I download the code ,and run "cmake ../.", there is configure error as below:

- cmake ../.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aws/aws-iot-device-sdk-cpp/build/third_party/rapidjson/download
[100%] Built target rapidjson
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindThreads.cmake:204 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:69 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by vareddy** [comment]
Hi @zhy989,
Thank you for using AWS IoT!
The above issue occurs when CMake cannot find the threading library used by the platform.
On investigating, it seems like CMake has a problem finding threads on some platforms as stated in this [StackOverflow post](https://stackoverflow.com/questions/15193785/how-to-get-cmake-to-recognize-pthread-on-ubuntu). Could you try changing [this](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/CMakeLists.txt#L2) line to `project(aws-iot-sdk-cpp C CXX)` and checking if that fixes it? 
Could you also provide more information about your platform as that would help us in tracking the occurrence of this issue. 
Please let us know if you have any more questions.
Thanks!
Varun

**Comment by liuszeng** [comment]
Hi @zhy989,

We have not heard from you for a while. We are closing the issue for now. Please feel free to open up a new thread if you still have questions.

Thanks,
Liusu
