### ISSUE TITLE
Can not use class of library

### ISSUE THREAD

**Issue by chaunnt** [aws/aws-iot-device-sdk-cpp#33]
Sorry for asking.
I compiled library and installed to PC (Ubuntu 14.04)
But when I use this library to a fresh C++ program (Code by Qt)
Classes can not be called.
After I trace down to header file
I got this in NetworkConnection.hpp
`AWS_API_EXPORT class NetworkConnection {`

But when I looked into macro "AWS_API_EXPORT", "__declspec(dllexport)" is blocked by defined macro.
```
#pragma once
#if defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
#ifdef _MSC_VER
#pragma warning(disable : 4251)
#endif // _MSC_VER

#ifdef USE_EXPORT
#define  AWS_API_EXPORT __declspec(dllexport)
#else // USE_EXPORT
#define AWS_API_EXPORT
#endif // USE_EXPORT
#else // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
#define AWS_API_EXPORT
#endif // defined (USE_WINDOWS_DLL_SEMANTICS) || defined (WIN32)
```
What is this purpose ? 

Note: I'm just try to build & use this library for native ubuntu C++ program

**Comment by vareddy** [comment]
Hi @chaunnt,
When you say install, did you  run `sudo make install`?
We have not tried using this library with Qt, hence we cannot comment on how it will behave with Qt code. 
The code block you provided only applies to Windows systems. For Linux systems, `AWS_API_EXPORT` translates to a blank string.
In this case as well, we will be able to investigate better after we look at the CMake output. 
Thanks!
Varun

**Comment by chaunnt** [comment]
Hi @vareddy 

> When you say install, did you run sudo make install?

Yes. I ran "sudo make install"
Here is the output

> ~/aws-iot-device-sdk-cpp-1.1.1/build$ sudo make install
> [ 37%] Built target aws-iot-sdk-cpp
> [ 43%] Built target aws-iot
> [ 56%] Built target aws-iot-integration-tests
> [ 59%] Built target gtest
> [ 65%] Built target gmock_main
> [ 70%] Built target gmock
> [ 73%] Built target gtest_main
> [ 88%] Built target aws-iot-unit-tests
> [ 94%] Built target pub-sub-sample
> [100%] Built target shadow-delta-sample
> Install the project...
> -- Install configuration: ""
> -- Installing: /usr/local/lib/libaws-iot-sdk-cpp.a
> -- Up-to-date: /usr/local/include
> -- Installing: /usr/local/include/NetworkConnection.hpp
> -- Installing: /usr/local/include/ResponseCode.hpp
> -- Installing: /usr/local/include/discovery
> -- Installing: /usr/local/include/discovery/Discovery.hpp
> -- Installing: /usr/local/include/discovery/DiscoveryResponse.hpp
> -- Installing: /usr/local/include/Action.hpp
> -- Installing: /usr/local/include/mqtt
> -- Installing: /usr/local/include/mqtt/Common.hpp
> -- Installing: /usr/local/include/mqtt/Client.hpp
> -- Installing: /usr/local/include/mqtt/Subscribe.hpp
> -- Installing: /usr/local/include/mqtt/Packet.hpp
> -- Installing: /usr/local/include/mqtt/GreengrassMqttClient.hpp
> -- Installing: /usr/local/include/mqtt/NetworkRead.hpp
> -- Installing: /usr/local/include/mqtt/Publish.hpp
> -- Installing: /usr/local/include/mqtt/ClientState.hpp
> -- Installing: /usr/local/include/mqtt/Connect.hpp
> -- Installing: /usr/local/include/shadow
> -- Installing: /usr/local/include/shadow/Shadow.hpp
> -- Installing: /usr/local/include/ClientCore.hpp
> -- Installing: /usr/local/include/util
> -- Installing: /usr/local/include/util/memory
> -- Installing: /usr/local/include/util/memory/stl
> -- Installing: /usr/local/include/util/memory/stl/StringStream.hpp
> -- Installing: /usr/local/include/util/memory/stl/Vector.hpp
> -- Installing: /usr/local/include/util/memory/stl/Map.hpp
> -- Installing: /usr/local/include/util/memory/stl/String.hpp
> -- Installing: /usr/local/include/util/memory/stl/Queue.hpp
> -- Installing: /usr/local/include/util/threading
> -- Installing: /usr/local/include/util/threading/ThreadTask.hpp
> -- Installing: /usr/local/include/util/logging
> -- Installing: /usr/local/include/util/logging/LogMacros.hpp
> -- Installing: /usr/local/include/util/logging/ConsoleLogSystem.hpp
> -- Installing: /usr/local/include/util/logging/LogSystemInterface.hpp
> -- Installing: /usr/local/include/util/logging/Logging.hpp
> -- Installing: /usr/local/include/util/logging/LogLevel.hpp
> -- Installing: /usr/local/include/util/logging/FormattedLogSystem.hpp
> -- Installing: /usr/local/include/util/JsonParser.hpp
> -- Installing: /usr/local/include/util/Utf8String.hpp
> -- Installing: /usr/local/include/util/Core_EXPORTS.hpp
> -- Installing: /usr/local/include/ClientCoreState.hpp

> The code block you provided only applies to Windows systems. For Linux systems, AWS_API_EXPORT translates to a blank string.
Yes. I know code is applied for Window, but I means why it is applied for window when I build it for Ubuntu (I use Ubuntu system to build). Because I thought it is cross-platform, isn't it ?

> For Linux systems, AWS_API_EXPORT translates to a blank string.
Yeah. That 's why I can not use classes of library, because library do not export any thing. 

Today, i will try to compile & use library in Window. But I hope if there is any solution for cross-platform.

**Comment by chaunnt** [comment]
I'm very sorry :(((((((((((((((((((((((
I'm so noob that I only look for classes.
When I review library, I recognize that I did not use namespace yet :(
It is fine now with calling "awsiotsdk::MqttClient client;"

Please help me close these issue
