### ISSUE TITLE
Resend Client Token

### ISSUE THREAD

**Issue by YeisonCL** [aws/aws-iot-device-sdk-cpp#34]
When I initialize the shadow of the device, the SDK creates a default client token, however, as this client token does not change with each request, it is not sent when I perform a "PerformUpdateAsync", how can I force the client token to be sent?

Thanks!

**Comment by vareddy** [comment]
Hi @YeisonCL ,
Thank you for your interest in AWS IoT!
If I understand you correctly, you want the client token to be sent in every `PerformUpdateAsync` request? Would this have to be sent in every request even if there is no other difference in the rest of the shadow json? 
Also could you please explain what your use case is and why you need the client token to be sent in every update (if you don't have to divulge any proprietary information that is)?
Please let us know if you have any more questions.
Thanks!
Varun

**Comment by vareddy** [comment]
Hi @YeisonCL ,
We haven't heard from you in over a week so we are closing this issue. Please feel free to open a new issue if you have any questions about the C++ SDK.
Thanks!
Varun
