### ISSUE TITLE
Build Error on RPI 

### ISSUE THREAD

**Issue by Fayazdeen** [aws/aws-iot-device-sdk-cpp#36]
Hi,

I have tried to build using cmake, I see following error 

> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/pi/surya/aws-iot-device-sdk-cpp/build/third_party/rapidjson/download
> [100%] Built target rapidjson
> CMake Error at /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
>   Could NOT find Threads (missing: Threads_FOUND)
> Call Stack (most recent call first):
>   /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/share/cmake-3.2/Modules/FindThreads.cmake:204 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:69 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pi/surya/aws-iot-device-sdk-cpp/build/CMakeFiles/CMakeOutput.log".
> See also "/home/pi/surya/aws-iot-device-sdk-cpp/build/CMakeFiles/CMakeError.log".

Please let me know how to fix it, Thanks in advance.

**Comment by Fayazdeen** [comment]
Upgrade to CMake 3.9 fixed the issue.Thanks

**Comment by hedeshianaws** [comment]
Thank you for your interest in AWS IoT. I'm glad you were able to resolve your issue. Please let us know if you have any other questions.
