### ISSUE TITLE
403 forbiden error on websocket connection

### ISSUE THREAD

**Issue by nesnes** [aws/aws-iot-device-sdk-cpp#38]
I'm testing the PubSub sample with the websocket configuration because opening the 8883 port isn't possible for my use-case.

Executing the sample, I'm facing a 403 Forbidden in the connection process
```
HTTP/1.1 403 Forbidden
content-type: application/json
content-length: 118
date: Wed, 13 Sep 2017 14:45:35 GMT
x-amzn-RequestId: XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX //hash replaced by XXX
connection: 
```
This error is leading to an out_of_range exception. Here is the call stack:
![image](https://user-images.githubusercontent.com/9192862/30385298-08bb825e-98a7-11e7-95cb-27ef3c1f1c36.png)

My config file looks like the following:
```
{
  "endpoint": "XXXXXXXXX.iot.XXXXXXX.amazonaws.com",
  "mqtt_port": 8883,
  "https_port": 443,
  "greengrass_discovery_port": 8443,
  "root_ca_relative_path": "certs/rootCA.crt",
  "device_certificate_relative_path": "certs/cert.pem",
  "device_private_key_relative_path": "certs/privkey.pem",
  "tls_handshake_timeout_msecs": 60000,
  "tls_read_timeout_msecs": 2000,
  "tls_write_timeout_msecs": 2000,
  "aws_region": "",
  "aws_access_key_id": "",
  "aws_secret_access_key": "",
  "aws_session_token": "",
  "client_id": "device_test",
  "thing_name": "device_test",
  "is_clean_session": true,
  "mqtt_command_timeout_msecs": 20000,
  "keepalive_interval_secs": 30,
  "minimum_reconnect_interval_secs": 1,
  "maximum_reconnect_interval_secs": 128,
  "maximum_acks_to_wait_for": 32,
  "action_processing_rate_hz": 5,
  "maximum_outgoing_action_queue_length": 32,
  "discover_action_timeout_msecs": 300000
}
```

And the certs folder is containing the mentioned files.

I didn't changed anything from the source code except solving two compilation issues where `std::bind` had to be replaced by `std::bind<ResponseCode>` [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/samples/PubSub/PubSub.cpp#L102) and [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/samples/PubSub/PubSub.cpp#L195).

Do you have any idea on how to solve this 403 issue and protect the out_of_range?

**Comment by vareddy** [comment]
Hi @nesnes,
Thank you for your interest in AWS IoT!
When you use WebSockets, you need to fill in your AWS access key and secret access key into the config file. The 403 error you see is expected as it is not able to authenticate with AWS IoT. 
Could you add in your access and secret key into the SampleConfig.json and try the sample?
Please let us know if you have any more questions.
Thanks!
Varun

**Comment by nesnes** [comment]
Thank you very much for your answer, it really helps!
Would you recommend one key per device or a master key?
The issue can be closed with your answer ;)

**Comment by nesnes** [comment]
Hi again,

A quick google search on how to create AWS access keys solve the forbidden issue. Thank you

However, I'm facing an ssl issue on a windows computer that blocks the PubSub sample: 

![image](https://user-images.githubusercontent.com/9192862/30547135-c725e85c-9c8e-11e7-8223-40c9da5e5f0b.png)

It seems to be a timestamp issue. Do you have a solution?

**Comment by vareddy** [comment]
Hi @nesnes,
Apologies for the late reply!
It seems like you need to reset the time in cmd to reflect the system time. Your system time is correct but it doesn't reflect in the cmd line. I am not sure why the mismatch is occurring.  
Could you try setting the time using the method shown here : http://www.wikihow.com/Change-the-Computer-Time-and-Date-Using-the-Command-Prompt.
Please let us know if you have any more questions.
Thanks!
Varun

**Comment by vareddy** [comment]
HI @nesnes ,
We haven't heard from you in a long time, hence we are closing this issue. Please open a **new issue** if you run into any problems with the SDK.
Thanks!
Varun
