### ISSUE TITLE
Missing disconnect callback?

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#4]
Hello,

I am trying to understand how the SDK handles connection state. When [auto-reconnect](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/include/mqtt/Client.hpp#L222) if set to false, SDK will not re-connect automatically after the `keep-alive` times out as set during [connect](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/include/mqtt/Client.hpp#L95) and the mqtt client will become disconnected. 

In the current SDK design, applications will not be able to receive information about this `auto-disconnect` since the SDK does not provide with a `disconnect callback`. aws-iot-device-sdk-embedded-C SDK provides us with such a callback [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_mqtt_client.h#L379).

Having a disconnect callback might be useful in cases when applications want to control the re-connection to AWS IoT or for some other book-keeping or resource cleanups etc.

I also saw that [ClientState caches the connection state](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/include/mqtt/ClientState.hpp#L40) and the mqtt clients return it when [IsConnected](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Client.cpp#L152) api is called. Having a disconnect callback can help in making this connection state consistent as well.

Am I missing something here?

**Comment by chaurah** [comment]
Hi @shekharhimanshu,
       This seems like an oversight. We definitely need to have a disconnect callback and notification. I have added a task to add this in the next release. For now, the only available notification is the response code from API calls unfortunately.

ClientState does cache the connection state but it is also updated in the Disconnect API which is called for cleanup whenever a disconnect or unrecoverable network state is detected. It should always have the correct information. That being said, I have been debating linking it to network layer changes as well. Do you notice any issues with the current implementation?

Please let me know if you have further questions.

Rahul

**Comment by shekharhimanshu** [comment]
Hello @chaurah,

Thats great. Will wait for the next release for the disconnect callback.

Yes, you are correct about the ClientState' connection state. Looks like I overlooked the part where the connection state was being updated. Thank you.

Linking the cached connection state to network layer changes would improve the usability but I am not sure if I have considered other design issues/goals of the SDK. So would wait for any update about this as well. Unfortunately, I have just started designing my application using this SDK and all my feedbacks are based upon the documentation present and the source code.

I will let you know if I find any issues during implementation/testing.

**Comment by chaurah** [comment]
Hi @shekharhimanshu,
        That sounds good. Please definitely let us know if you find anything I can help with. In the meantime, I will keep this issue open until we have added a disconnect callback to the Disconnect Action.

Rahul

**Comment by chaurah** [comment]
This issue has been resolved with v1.1 of the SDK Please reopen if you further questions.

Rahul

**Comment by shekharhimanshu** [comment]
Hello,

Could you please explain when will this disconnect callback be called?
I could not find anything in the documentation.

**Comment by shekharhimanshu** [comment]
Also, I do not see any reopen issue button. Missing permission?

**Comment by shekharhimanshu** [comment]
I have opened a new issue instead. #17
