### ISSUE TITLE
Disconnect callback context data is always a nullptr

### ISSUE THREAD

**Issue by mzanetti** [aws/aws-iot-device-sdk-cpp#42]
Using this code:
```MqttClient::Create(m_networkConnection, std::chrono::milliseconds(30000), &onDisconnectedCallback, std::shared_ptr<DisconnectCallbackContextData>(this));```

whenever the onDisconnectedCallback is called, the p_app_handler_data is null.

**Comment by vareddy** [comment]
HI @mzanetti ,
We will include your fix in the next release of the SDK.
Thanks!
Varun
