### ISSUE TITLE
ERR_remove_state deprecated in 1.0.2

### ISSUE THREAD

**Issue by aaronovz1** [aws/aws-iot-device-sdk-cpp#48]
`ERR_remove_state` is deprecated in 1.0.2. Can we safely switch to `ERR_remove_thread_state`?

**Comment by vareddy** [comment]
Hi @aaronovz1 ,
This fix for this is currently in master, if you look at this [commit](https://github.com/aws/aws-iot-device-sdk-cpp/commit/e98e8e9412fadb4bfae70ff6139a54ca11979c89#diff-3180c998a25b2617fc636a7b499701e7), but we haven't made a release with these changes yet. 
Please let us know if you have any more questions. Thank you for your interest in AWS IoT!
Thanks,
Varun

**Comment by aaronovz1** [comment]
I see. Thanks!
