### ISSUE TITLE
shadow methods should be const-correct

### ISSUE THREAD

**Issue by larsonmpdx** [aws/aws-iot-device-sdk-cpp#49]
see here for example:
https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/shadow/Shadow.cpp#L64
mqtt_command_timeout, thing_name, client_token_prefix should be const.  haven't looked at the shared_ptr, maybe that too.  probably the whole codebase could use a once-over to fix this

**Comment by chaurah** [comment]
Hi @larsonmpdx,
       Thank you for pointing this out. You are correct of course. I have an internal task to revisit the APIs for stuff like this when we move to v2.0. I will close this issue for now since we won't be addressing this for a while, v2.0 is several months away. But please rest assured, we will definitely address this.

As always, please keep the suggestions coming. Your help has been invaluable in improving the quality of the SDK.

Rahul
