### ISSUE TITLE
calling AddShadowSubscription() after connect() disconnects client

### ISSUE THREAD

**Issue by larsonmpdx** [aws/aws-iot-device-sdk-cpp#50]
with a client that is more or less copied from 

https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/samples/ShadowDelta/ShadowDelta.cpp

using openssl and the newest sdk

I might be making some simple error.  Is there a reason this might be happening?

**Comment by vareddy** [comment]
Hi @larsonmpdx , 
Have you tried looking at the Cloudwatch logs for your account? There may be more information as to why the disconnect happened. Could you could paste the logs here after removing any account specific information present in it?
Thanks!
Varun

**Comment by larsonmpdx** [comment]
```
2017-11-08 08:05:26.972 TRACEID:deb245ad-08f0-feca-84df-91fc16b71792 PRINCIPALID:d96b904de5dd079fcab4a4bf16d51af296b7de12f7acc3901359e9af009b0439 [INFO] EVENT:MQTT Client Connect MESSAGE:Connect Status: SUCCESS
2017-11-08 08:05:26.972 TRACEID:deb245ad-08f0-feca-84df-91fc16b71792 PRINCIPALID:d96b904de5dd079fcab4a4bf16d51af296b7de12f7acc3901359e9af009b0439 [INFO] EVENT:MQTT Client Connect MESSAGE: IpAddress: 54.212.197.72 SourcePort: 58962
2017-11-08 08:05:27.008 TRACEID:73d16f81-227d-d505-85ef-c4ed23c8e553 PRINCIPALID:d96b904de5dd079fcab4a4bf16d51af296b7de12f7acc3901359e9af009b0439 [DEBUG] EVENT:KinesisActionStart TOPICNAME:$aws/events/presence/connected/4947bd70-c3fd-11e7-810d-a1ddbf03fe89 CLIENTID:N/A MESSAGE:Starting execution of KinesisAction on topic $aws/events/presence/connected/4947bd70-c3fd-11e7-810d-a1ddbf03fe89
2017-11-08 08:05:27.056 TRACEID:99a57e03-e53c-52cc-b77d-134e618639ac PRINCIPALID:d96b904de5dd079fcab4a4bf16d51af296b7de12f7acc3901359e9af009b0439 [ERROR] EVENT:MQTTClient Subscribe TOPICNAME:$aws/things/4947bd70-c3fd-11e7-810d-a1ddbf03fe89/shadow/get/accepted,$aws/things/4947bd70-c3fd-11e7-810d-a1ddbf03fe89/shadow/get/rejected,$aws/things/4947bd70-c3fd-11e7-810d-a1ddbf03fe89/shadow/update/accepted,$aws/things/4947bd70-c3fd-11e7-810d-a1ddbf03fe89/shadow/update/rejected,$aws/things/4947bd70-c3fd-11e7-810d-a1ddbf03fe89/shadow/delete/accepted,$aws/things/4947bd70-c3fd-11e7-810d-a1ddbf03fe89/shadow/delete/rejected,$aws/things/4947bd70-c3fd-11e7-810d-a1ddbf03fe89/shadow/update/delta MESSAGE:Subscribe Status: AUTHORIZATION_ERROR
2017-11-08 08:05:27.056 TRACEID:99a57e03-e53c-52cc-b77d-134e618639ac PRINCIPALID:d96b904de5dd079fcab4a4bf16d51af296b7de12f7acc3901359e9af009b0439 [INFO] EVENT:MQTTClient Subscribe MESSAGE: IpAddress: 54.212.197.72 SourcePort: 58962
2017-11-08 08:05:27.062 TRACEID:fb09cc27-0714-0d47-7408-13393df34a69 PRINCIPALID:d96b904de5dd079fcab4a4bf16d51af296b7de12f7acc3901359e9af009b0439 [INFO] EVENT:MQTT Client Disconnect MESSAGE:Disconnect Status: SUCCESS
2017-11-08 08:05:27.062 TRACEID:fb09cc27-0714-0d47-7408-13393df34a69 PRINCIPALID:d96b904de5dd079fcab4a4bf16d51af296b7de12f7acc3901359e9af009b0439 [INFO] EVENT:MQTT Client Disconnect MESSAGE: IpAddress: 54.212.197.72 SourcePort: 58962
```

would the AUTHORIZATION_ERROR on the subscribe call do this?  I don't have good debug output at the client side that matches this, is it the server initiating the disconnect?

**Comment by vareddy** [comment]
Hi @larsonmpdx ,
It looks more like a policy issue. Could you try the same certs with the ShadowDelta sample and see if you get the same error? The shadow subscribe should fail and the sample should disconnect and quit if it is a policy issue. 
Thanks!
Varun

**Comment by larsonmpdx** [comment]
ok, that also fails.  Can you give an example of a policy that allows this shadow functionality?  All of the documentation I can find is some simple "allow all" wildcard or if it's constrained to a device it skips the use of thing policy variables (http://docs.aws.amazon.com/iot/latest/developerguide/thing-policy-variables.html) and doesn't give specific recommendations about best practices.

**Comment by vareddy** [comment]
Hi @larsonmpdx , 
Here is an example policy that uses thing policy variables:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:UpdateThingShadow",
      "Resource": "arn:aws:iot:us-east-1:<ACCOUNT ID>:thing/{iot:Connection.Thing.ThingTypeName}"
    },
    {
      "Effect": "Allow",
      "Action": "iot:GetThingShadow",
      "Resource": "arn:aws:iot:us-east-1:<ACCOUNT ID>:thing/{iot:Connection.Thing.ThingTypeName}"
    },
    {
      "Effect": "Allow",
      "Action": "iot:DeleteThingShadow",
      "Resource": "arn:aws:iot:us-east-1:<ACCOUNT ID>:thing/{iot:Connection.Thing.ThingTypeName}"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Connect",
      "Resource": "arn:aws:iot:us-east-1:<ACCOUNT ID>:client/<THING_NAME>"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Subscribe",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Publish",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Receive",
      "Resource": "*"
    }
  ]
}
```
For more information on how to use thing-policy variables, please refer to [here](http://docs.aws.amazon.com/iot/latest/developerguide/thing-policy-examples.html)
Let me know if this works for your use case.
Thanks!
Varun

**Comment by larsonmpdx** [comment]
Thank you, that works.  Can you explain what was happening?  Does the server disconnect any client that has an authorization error?

**Comment by vareddy** [comment]
Hi @larsonmpdx ,
Yes the server disconnects the client, it has no other way of communicating an authorization error to the device. There is more information about this in #25 as the issue was essentially the same.
Thanks!
Varun

**Comment by larsonmpdx** [comment]
how can I restrict the allowed subscription topics to only what's needed for the shadow?  I tried this policy with an asterisk after "shadow" and it failed:
```
    {
      "Effect": "Allow",
      "Action": "iot:Subscribe",
      "Resource": [
            "arn:aws:iot:iot:us-west-2:123456789012:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/*"
        ]
    },
```

**Comment by vareddy** [comment]
Hi @larsonmpdx ,
The resource should not be topic, but topicfilter, like so:
```
"Resource": [
            "arn:aws:iot:iot:us-west-2:123456789012:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/*"
        ]
```
Let me know if that works. 
Thanks!
Varun

**Comment by larsonmpdx** [comment]
oh, good catch.  that isn't working.  I found this note about wildcards in the shadow topic names:

https://forums.aws.amazon.com/thread.jspa?threadID=219158

it seems to suggest changing the * to #, I tried it both ways and it doesn't work

**Comment by vareddy** [comment]
Hi @larsonmpdx , 
I just tested the resource I posted in the last reply and it worked for me. 
It's also recommended to not use wildcards as the Shadow specification can change to include more topics in the future, as stated [here](http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-mqtt.html). If you do not mind using individual topics, you can have multiple topics in the resource as shown below: 
```
"Resource": [
        "arn:aws:iot:us-east-1:123456789012:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/get/accepted",
        "arn:aws:iot:us-east-1:123456789012:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/get/rejected",
        "arn:aws:iot:us-east-1:123456789012:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/delta",
        "arn:aws:iot:us-east-1:123456789012:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/document",
        "arn:aws:iot:us-east-1:123456789012:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/accepted",
        "arn:aws:iot:us-east-1:123456789012:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/rejected",
        "arn:aws:iot:us-east-1:123456789012:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/delete/accepted",
        "arn:aws:iot:us-east-1:123456789012:topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/delete/rejected"
      ]
```
The forum post states that the if you want to subscribe to wildcard topics, you use the MQTT wildcards i.e. for example, if your device itself is subscribing to `/this/is/+/topic/wildcard` and `/this/is/+/topic/wildcard2`, then your topic filter will be `/this/is/+/topic/*`.
Thanks!
Varun

**Comment by larsonmpdx** [comment]
I found the problem, the example had "iot:iot" in it instead of "iot"

I think policies that include the thing name variable are OK with wildcards.  that should mean a malicious device can only access its own resources, even if it gets more types of resources in the future

I added a publish limit like this:
```
    {
      "Effect": "Allow",
      "Action": "iot:Publish",
      "Resource": [
        "arn:aws:iot:us-west-2:123456789012:topic/intake",
        "arn:aws:iot:us-west-2:123456789012:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/*"
      ]
    },
```

and also the "can connect only if using the attached cert" rule:
```
{
      "Effect": "Allow",
      "Action": "iot:Connect",
      "Resource": [
        "*"
      ],
      "Condition": {
        "Bool": {
          "iot:Connection.Thing.IsAttached": [
            "true"
          ]
        }
      }
    },
```

now I feel pretty good about the policy overall.  thanks for all the help!

**Comment by vareddy** [comment]
Hi @larsonmpdx 
Sorry about that, I corrected it in my policy but I forgot to post the corrected version where I removed the extra :iot. Good to know it worked! I'll close this issue, please open another issue if you have any more questions. 
Thanks!
Varun
