### ISSUE TITLE
Unnecessary clutter in stdout

### ISSUE THREAD

**Issue by rich-g** [aws/aws-iot-device-sdk-cpp#51]
The following messages are unconditionally printed to stdout when a thread is killed:

https://github.com/aws/aws-iot-device-sdk-cpp/blob/c20c9e9060ff5ee687636d41c1e508d3ef91ce75/src/util/threading/ThreadTask.cpp#L35
https://github.com/aws/aws-iot-device-sdk-cpp/blob/c20c9e9060ff5ee687636d41c1e508d3ef91ce75/src/util/threading/ThreadTask.cpp#L43

This seems a bit odd, and it probably makes more sense for these to be AWS_LOG_DEBUG or AWS_LOG_TRACE messages instead.

**Comment by vareddy** [comment]
Hi @rich-g ,
Yes, these would be better if they were AWS_LOG_DEBUG. I will push a fix to master after making the changes. 
Thanks for the suggestion! They play an important role in improving the SDK.
Varun
