### ISSUE TITLE
src/mqtt/connect.cpp: comparison is always false due to limited range of data type

### ISSUE THREAD

**Issue by larsonmpdx** [aws/aws-iot-device-sdk-cpp#54]
these comparisons are flagged by clang -wtype-limits.  this causes the code after the comparison to never be executed:

https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Connect.cpp#L137
https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Connect.cpp#L163

this one is similar but just some extra code:

https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Connect.cpp#L197

**Comment by vareddy** [comment]
Hi @larsonmpdx , 
I have made the fix for this and I'm currently running it through our internal test pipeline. I will commit to master after the testing completes.
Thanks!
Varun
