### ISSUE TITLE
3 sample projects does not show up in VS solution automatically

### ISSUE THREAD

**Issue by hxl9654** [aws/aws-iot-device-sdk-cpp#55]
discovery-sample, robot-arm-sample, switch-sample  does not show up in VS solution automatically.
I check the build/samples/Discovery, etc. The projects are already compile by Cmake.
It can be add to the solution manually. 
So, I think this maybe a bug.

**Comment by hxl9654** [comment]
I compile on Win10 64bit with VS 2017, cmake use default configure.

**Comment by vareddy** [comment]
Hi @hxl9654 ,
Thank you for your interest in AWS IoT!
These three projects were intentionally excluded from the default build of the SDK as they require additional setup to be completed before they can be run successfully, namely the setting up of a Greengrass Core with the appropriate  subscriptions and devices added to that Core. If you want them to be compiled by default, you can remove the `EXCLUDE_FROM_ALL` target property [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/CMakeLists.txt#L166) for the above samples. 
Please let us know if that works for you. 
Thanks!
Varun

**Comment by vareddy** [comment]
Hi @hxl9654 ,
We haven't heard from you in some time so we are closing this issue. If you have any problems, please **open a new issue**.
Thanks!
Varun
