### ISSUE TITLE
Garbled text at compile in CMD, on Win10 zh_CN

### ISSUE THREAD

**Issue by hxl9654** [aws/aws-iot-device-sdk-cpp#56]
as the pic below.
I tried common Chinese charset, such as UTF-8, GBK, GB2132. And doesn't work.
![1](https://user-images.githubusercontent.com/6624983/33198638-51f58bc8-d127-11e7-98bf-e060740cae12.png)

**Comment by vareddy** [comment]
Hi @hxl9654 ,
Thank you for your interest in the AWS IoT SDK! 
This seems to be related to the issues in Visual Studio itself and not with the way the SDK is using CMake. I was able to locate the following two issues being tracked related to the garbled output: 
https://github.com/vector-of-bool/vscode-cmake-tools/issues/153
https://github.com/Microsoft/vscode/issues/974 
I am closing this issue as it is unrelated to the SDK itself.
Please let us know if you have any more questions and **please open another issue** if you do as we do not have effective tracking for closed issues.  
Thanks!
Varun
