### ISSUE TITLE
Feature request: PING api

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#57]
Would be nice to have such an api to allow users to manually send a PING to AWS IoT broker.

**Comment by liuszeng** [comment]
Hi @shekharhimanshu ,

Thank you very much for your feedback to AWS IoT Device SDK for C++. I have created an internal tracker for this feature request. We will take that into consideration as we are planning our future releases.

Thanks,
Liusu

**Comment by certabitmh** [comment]
Would appreciate this feature, since MqttClient -> IsConnected() API doesn't seem to be relieable
