### ISSUE TITLE
Install doesn't install OpenSSLConnection under aws shared library

### ISSUE THREAD

**Issue by accesio** [aws/aws-iot-device-sdk-cpp#58]
Hi,

A number of your samples ( and eventually user code ) rely on OpenSSLConnection.{cpp,hpp}   .  However, these two files don't make it into the final shared library or into the install include directory. This makes it difficult to build samples that look like Amazon's because the user then has to include the OpenSSLConnection files in their own project.

Just a thought that this could be installed and included in the shared library that is constructed.

**Comment by chaurah** [comment]
Hi @accesio,
    We are explicitly ignoring it. The design specifically calls for the Network wrapper code to be a part of the user code and not the core SDK. This is to allow users to write their own Network wrappers and use them without any changes to the core SDK as they see fit. We will definitely not be installing those files. This applies to the samples as well. The core SDK is compiled as a separate library and the network wrapper is being built with the sample. You can see this in the sample CMakeLists.txt file. For the PubSub sample, the pre-built SDK library is linked to [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/samples/PubSub/CMakeLists.txt#L54) and the Network layer code is included with the sample code [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/samples/PubSub/CMakeLists.txt#L77).

Closing this issue. Please do feel free to open new issues for other suggestions that you may have for the SDK.

Rahul
