### ISSUE TITLE
Support for "Authorizing Direct Calls to AWS Services"

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-iot-device-sdk-cpp#59]
https://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html

Is support for this going to be added soon?

**Comment by chaurah** [comment]
Hi @jonsmirl,
     We do not have plans to add this support at the moment. You should be able to write an Action to do this without much work however. The Discover action would be a good starting point.

I will update this issue once we have a better idea of when support for this will be added. Please do let us know if you have further questions.

Rahul

**Comment by jonsmirl** [comment]
After looking at the various SDKs, it would probably be better to add support for this into the main AWS CPP SDK. That SDK already uses curl for http and could be extended to support client certificates. Plus you need that SDK to use with the credentials you receive.

**Comment by ramkishb** [comment]
Hi @jonsmirl,

The feature is supported in the Node.js/JavasScript AWS SDK https://github.com/aws/aws-sdk-js by using the RemoteCredentials credential provider. We do not have it in the CPP SDK at present. Thanks for your feedback, we will have it in our task list and prioritize appropriately.

Regards,
Ramkishore

**Comment by chaurah** [comment]
As @ramkishb has mentioned, this will be a part of the AWS Cpp SDK going forward as a credential provider. Closing this issue.

Rahul
