### ISSUE TITLE
Disconnection-Callback while stopping broker gracefully

### ISSUE THREAD

**Issue by karanparmar26** [aws/aws-iot-device-sdk-cpp#60]
Hello,

I am just trying to get a disconnection callback when connected broker is stopped gracefully,
current sdk is working perfectly in the case of disconnection callback, when network connectivity goes,
but if the connected broker is stopped, in that case sdk immidiately terminates.

correct me if i am doing something wrong.

**Comment by vareddy** [comment]
Hi @karanparmar26,
Thank you for your interest in AWS IoT!
When you say connected broker, do you mean the Greengrass Core?
Thanks!
Varun

**Comment by karanparmar26** [comment]
Yes, i am connecting to some other mqtt broker over openSSL.
And when i am stop that broker service,  sdk terminates immidiately.

**Comment by vareddy** [comment]
Hi @karanparmar26,
I have been able to reproduce the issue and have a potential fix for it.
Could you modify the [OpenSSLConnection.cpp](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/network/OpenSSL/OpenSSLConnection.cpp#L438) header file and add this line after the line indicated:
```signal(SIGPIPE, SIG_IGN);```
Please try the above and let us know if that works in your case.
Thanks!
Varun

**Comment by karanparmar26** [comment]
Hi  @vareddy 

Yes i updated the OpenSSLConnection.cpp as you mentioned, and it worked.
Now i am successfully able to get a disconnection callback, when the broker is stopped gracefully.

Thanks!
Karan

**Comment by vareddy** [comment]
Hi @karanparmar26,
That's great! I'll test the fix more on our end and publish a fix to master after we complete our testing. I'll keep this issue open till I publish the fix. 
Thanks!
Varun

**Comment by vareddy** [comment]
Hi @karanparmar26,
I've pushed the fix to master. I moved the signal ignore code into the init function as it needs to be called only once. Please update your code if required. 
Thanks!
Varun
