### ISSUE TITLE
Subscribing to an already subscribed topic will result in timeout (SDK error -703)

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#61]
Hello,

I noticed that subscribing to an already subscribed topic results in [-703 error](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/include/ResponseCode.hpp#L126).

This happens because [SubscribeActionAsync::PerformAction](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Subscribe.cpp#L222) filters out already subscribed topics [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Subscribe.cpp#L255) but [does not check](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Subscribe.cpp#L269) if the filtered topic list is empty or not before sending the SUB packet.

The timeout occurs because the client is waiting for an ACK which is never coming since nothing was sent to the server.

I would recommend checking for empty sub packet [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Subscribe.cpp#L269) before writing to network to resolve this issue. (I am assuming that the behavior is not by design. If so please let me know.)

**Comment by vareddy** [comment]
Hi @shekharhimanshu,
That is correct, thanks for the catch! Ideally it should return an already subscribed error code as none of the other error codes match the specific case of subscribing to a topic that is already subscribed to. A timeout is very misleading in this case. 
I will make a fix for this and publish to master after testing. 
Thanks!
Varun

**Comment by shekharhimanshu** [comment]
>Ideally it should return an already subscribed error code as none of the other error codes match the specific case of subscribing to a topic that is already subscribed to.

Or the sdk do not report any error and just return without doing anything (since already subscribed).
I think this approach is in line with the current SDK design (since it filters out already subscribed topics at the moment)

**Comment by certabitmh** [comment]
Would be nice to have an API function to check if subscriptions are active or "broken". Sometimes face the issue that I don' receive delta callbacks although subscribed to topics.
