### ISSUE TITLE
ShadowDelta sample code hangs in Connect call.

### ISSUE THREAD

**Issue by sapnatodwal** [aws/aws-iot-device-sdk-cpp#62]
I have verified the certificates using the call:
openssl s_client -connect XXXXXXXXXX.us-XXXX-2.amazonaws.com:8883 -CAfile ./certs/rootCA.crt -cert ./certs/cert.pem -key ./certs/privkey.pem 

However within the code I am seeing the error -407 , i.e SSL connection was closed. Any idea why this could be happening or what am I missing in my configuration below:

{
  "endpoint": "xxxxxxxxxx.iot.us-xxxx-2.amazonaws.com",
  "mqtt_port": 8883,
  "https_port": 443,
  "greengrass_discovery_port": 8443,
  "root_ca_relative_path": "certs/rootCA.crt",
  "device_certificate_relative_path": "certs/cert.pem",
  "device_private_key_relative_path": "certs/privkey.pem",
  "tls_handshake_timeout_msecs": 60000,
  "tls_read_timeout_msecs": 2000,
  "tls_write_timeout_msecs": 2000,
  "aws_region": "",
  "aws_access_key_id": "",
  "aws_secret_access_key": "",
  "aws_session_token": "",
  "client_id": "test-device-01",
  "thing_name": "test-device-01",
  "is_clean_session": true,
  "mqtt_command_timeout_msecs": 30000,
  "keepalive_interval_secs": 600,
  "minimum_reconnect_interval_secs": 1,
  "maximum_reconnect_interval_secs": 128,
  "maximum_acks_to_wait_for": 32,
  "action_processing_rate_hz": 5,
  "maximum_outgoing_action_queue_length": 32,
  "discover_action_timeout_msecs": 300000
}

**Comment by liuszeng** [comment]
Hi @sapnatodwal ,

Thank you very much for using AWS IoT Device SDK for C++.

Can you attach the IoT policy that you have associated with the certificate in use?

Thanks,
Liusu

**Comment by sapnatodwal** [comment]
Actually I did not attach any IoT policy to the certificate, can you please help with that ?

Thanks,
Sapna

**Comment by liuszeng** [comment]
Hi @sapnatodwal ,

You can take a look at the following guidance:
https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdk-setup.html

Search for "attach a policy" and you should be able to find step-by-step guide on associating a policy with the certificate.

Note that an AWS IoT Policy defines the action/resource that the client who presents the certificate is allowed to operate/operate on. You will need to make sure that your policy grants enough permission for the sample you are going to run.

As for the policy content, you can take a look at the following documentation:
https://docs.aws.amazon.com/iot/latest/developerguide/pub-sub-policy.html

For simplicity for testing, you can use:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

Note that this policy allows all actions on all resources. Certificate owner will be able to connect/publish/subscribe/unsubscribe with any clientId/topic/topicFilter. You might want to scope the permissions as you are building your own application.

Hope the above helps.

Thanks,
Liusu

Hope the above helps.

Thanks,
Liusu

**Comment by sapnatodwal** [comment]
Thanks Liusu for your help. I was able to resolve this problem. However I have a question : Is there a way to create a new thing as well as create certificates for this thing using this SDK.

**Comment by liuszeng** [comment]
Hi @sapnatodwal ,

Glad to know it is working for you.

For your follow-up question, creating a thing and creating a certificate is the control plane APIs to manage your AWS IoT related resource. The proper SDKs you should be looking at is the AWS SDK:
C++: https://sdk.amazonaws.com/cpp/api/LATEST/_io_t_client_8h.html

Thanks,
Liusu

**Comment by sapnatodwal** [comment]
Liusu,
I tried to make the postman call for the following API:
POST /keys-and-certificate?setAsActive=true

I get the following error:
{
    "message": "Not Found",
    "traceId": "8c4eb734-fd44-0696-86c4-c1138317740c"
}

Can you please help with what am I missing here .Afaik I am using the correct access and the secret key for my account. Thanks !

**Comment by fengsongAWS** [comment]
Hi @sapnatodwal ,
This repo is specifically for AWS IoT Device SDK questions and problems. If you have questions on generic IoT question, you can look up or create a thread on AWS IoT Forum. https://forums.aws.amazon.com/forum.jspa?forumID=210 

Thanks for your interest in AWS IoT Device SDK.

**Comment by chaurah** [comment]
The discussion seems to have moved on to the AWS Cpp SDK. Closing this issue. Please feel free to open a new issue if you have further questions @sapnatodwal.

Rahul
