### ISSUE TITLE
Unsubscribing a topic does not "deactivate" the corresponding subscription

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#64]
Hello,

Just wanted to confirm the spec here. Consider the following situation:

```
- Create a subscription, say SubA with topic, say TopA
- Use this SubA to call subscribe
- My mqtt client is now subscribed to TopA
- SubA->isActive is now true
- Retain SubA
- Unsubscribe to TopA
- SubA->isActive is still true
```

After the above sequence, my expectation was that `SubA->isActive` should return false so as to make the specification more consistent.

What do you think?

**Comment by chaurah** [comment]
Hi @shekharhimanshu,
   I simply erased SubA from the subscription map. Do you have a use case where the callback is not sufficient and you are using the SubA object for other purposes?

Rahul

**Comment by shekharhimanshu** [comment]
Hi @chaurah 

Yes, I saw your implementation and indeed `Subscribe -> Unsubscribe -> Subscribe` for the same topic will work without any issues.

>Do you have a use case where the callback is not sufficient and you are using the SubA object for other purposes?

No. I dont. Callback is sufficient for my current use cases.

I was writing acceptance tests for this SDK:
`isActive_BecomesTrueWhenSubscribed` and `isActive_BecomesFalseWhenUnsubscribed`

and thats when I realized this behavior and thought should share this with you.

**Comment by chaurah** [comment]
I see what you mean. I think it should be simple enough to make sure the Subscription is set to false before we free the shared pointer. That way the subscription object can be reused as well if needed.
I will close this issue for now and add a task in my backlog. Thanks for sharing the info and as always, please feel free to open another issue if i can help further :)

Rahul
