### ISSUE TITLE
Possible invalid read inside mqtt/Client

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#66]
Mqtt client destruct sequence is as follows:
```
MqttClient::~MqttClient() {
        if (IsConnected()) {
            ResponseCode rc = Disconnect(p_client_state_->GetMqttCommandTimeout());
            if (ResponseCode::SUCCESS != rc) {
                AWS_LOG_ERROR(MQTT_CLIENT_LOG_TAG, "Disconnect returned error while destroying MQTT Client. %s",
                              ResponseHelper::ToString(rc).c_str());
            }
        }

        // p_client_state_.action_map_ and p_client_state_.outbound_action_queue_ retains p_client_state_
        // hence, calling p_client_state_->RegisterAction() or p_client_state_->EnqueueOutboundAction() introduces cyclic references inside p_client_state_
        // make sure that p_client_state_.action_map_ and p_client_state_.outbound_action_queue_ are cleared prior to p_client_state_ destructor
        // to break the cyclic references.
        p_client_state_->ClearRegisteredActions();
        p_client_state_->ClearOutboundActionQueue();
    }
```

To sum up, the destructor:
- disconnects client (if connected)
- clears registered actions and outbound action queue
- releases `p_client_state_` and other retained instances

Note that `p_client_state_` [waits for all the running threads to finish](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/ClientCore.cpp#L95).

Now consider the following test scenario:
```
- subscribe to a topic /foo
- wait for first message to arrive in topic /foo
- terminate the test once first message is received
```
Above test should reproduce the Invalid read when run under Valgrind. 

Here's why:
NetworkRead class receives the message and calls the callback [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/NetworkRead.cpp#L245). After calling the callback, [it enqueues an outbound action for Puback if QoS is 1](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/NetworkRead.cpp#L254...L260).

The test on the other hand does not wait for the Puback to finish (since it has no idea about it) and t terminates -> freeing the mqtt instance -> clearing registered actions and outbound queue -> thus releasing the [PubackActionAsync](https://github.com/aws/aws-iot-device-sdk-cpp/blob/63e8ce25e6b282719d112f3f58966cc1e78d271b/src/mqtt/Publish.cpp#L218) created by NetworkRead for sending Puback to the server [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/NetworkRead.cpp#L260). 

Since `Actions` are only retained inside Action list or outbound queues, they should not be cleared until all running threads are gracefully shutdown.

I recommend changing the `mqtt/Client`'s destruct sequence to as follows:
- disconnect the client (if connected)
- wait for all running threads to stop
   - Just need to clear the threads map as done [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/ClientCore.cpp#L95)
- clear registered actions and outbound action queue
- release `p_client_state_` and other retained instances

**Comment by vareddy** [comment]
Hi @shekharhimanshu ,
It looks like you are correct, the destructor does not wait for the threads to shutdown gracefully. I will make the above changes and test it in valgrind and update this issue with my findings.
Thanks for the catch!
Varun
