### ISSUE TITLE
aws-iot-devide-sdk build in visual studio linker errors

### ISSUE THREAD

**Issue by TejaswiniiB** [aws/aws-iot-device-sdk-cpp#69]
Hi, I want aws-iot-devide-sdk for windows. I downloaded this repo from release branch, have placed certificates in mentioned folder, ran cmake as mentioned in README. Build was successful. Now I have a visual studio project ALL_BUILD.vcxproj inside builds dir which I created, I need to build it and get executables for examples provided. Am I right? But after I open ALL_BUILD.vcxproj with visual studio and build, I am getting many errors like : 

`
Error	LNK2019	unresolved external symbol _CRYPTO_cleanup_all_ex_data referenced in function "public: __thiscall awsiotsdk::network::OpenSSLInitializer::~OpenSSLInitializer(void)" (??1OpenSSLInitializer@network@awsiotsdk@@QAE@XZ)	pub-sub-sample	aws-iot-device-sdk-cpp-release\aws-iot-device-sdk-cpp-release\builds\samples\PubSub\OpenSSLConnection.obj	1	
`

Can anyone please tell me how to overcome this and get successful build?
 Thankyou :)

**Comment by chamber-wang** [comment]
Hi TejawiniiB,

As I know, you are unable to compile the iot-sdk directly by visual studio directly. 
Instead, please refer to the following link
https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/Platform.md

It mentioned that we need install some utility first
OpenSSL, cMake....

After settle down these utility successfully. Enter the \build folder of  source code you download from github. (Should be \aws-iot-device-sdk-cpp\build something...)

Then type **cmake -G "Visual Studio 15 2017 Win64" -Dgtest_force_shared_crt=TRUE ../.**
This will start the source code build..

Enjoy and Good luck!
Chamber Wang

**Comment by TejaswiniiB** [comment]
I'm getting  "Device Private Key Loading error" for pubsub example, even after I enter correct names of certificate, keys names in .config files. Does anyone know why?

**Comment by TejaswiniiB** [comment]
Hi, while running pubsub example, I am getting this error:
`509 [OpenSSL Wrapper] [17020] [awsiotsdk::network::OpenSSLConnection::PerformSSLConnect:L345] : TCP Connection error`

Can anyone tell why?

**Comment by vareddy** [comment]
Hi @TejaswiniiB ,
Has your issue been solved? If yes, could you close this issue?
Thank you for your interest in AWS IoT!
Varun
