### ISSUE TITLE
add option for -fPIC compiler flag when building a static library on Linux

### ISSUE THREAD

**Issue by nkowdley** [aws/aws-iot-device-sdk-cpp#71]
Currently, I am trying to build a Shared Library which will link against a static version of this sdk.  

I keep getting an error on using the -fpic compiler flag, exactly like this issue https://github.com/aws/aws-sdk-cpp/issues/77.

Is there a reason why this hasn't been added as a CMake Option for this SDK?  If there isn't, I can make a MR to add this in.

**Comment by vareddy** [comment]
HI @nkowdley,
Thank you for your interest in the AWS IoT SDK.
This is a valid fix. If you could make a pull request, we will test the changes internally and merge it after we are done. 
Thanks!
Varun
