### ISSUE TITLE
Compile the aws-iot-device-sdk-cpp with Visual Studio Win64

### ISSUE THREAD

**Issue by chamber-wang** [aws/aws-iot-device-sdk-cpp#72]
Does anyone in this forum use visual studio 2017 for build and development? 
Basically, I use following command to generate makefile for VS2017.
cmake -G "Visual Studio 15 2017 Win64" -Dgtest_force_shared_crt=TRUE ../.

However, after I resolve some minor compiler issues, I still suffer 44 warning messages and would like to consult with you before moving forward. For sure, I am  willing to commit the minor patch for build under visual studio 2017 if necessary, please advise. 

1.) SIGPIPE not support under Windows platform 
#line 156 of \network\OpenSSL\OpenSSLConnection.cpp
Resolve this error by compiler "Preprocessor Statements #ifdef"

2.) unicode format encoding scheme.
\include\gtest\internal\gtest-internal.h
warning C4819:The file contains a character that cannot be represented in the current code page (950).
Resolve this by save as unicode format.

3.) Type conversion between 'unsigned int' to 'uint16_t'. 
3.a) stdint.h in Visual Studio platform define uint_16_t as "unsigned int"
3.b) SOCKET need type conversion to UINT_PTR instead of int.

Chamber Wang

**Comment by chaurah** [comment]
Hi @chamber-wang,
      We haven't tested this under VS2017 yet. From the issues you mentioned, the first one will be resolved in a fix that should go out soon. The second one seems to be in gtest, we can't resolve issues in dependencies directly. For the rest, if you're willing to submit a pull request, we'll be happy to merge it in as long as it doesn't affect other platforms. I will add a backlog task to fix all warnings in visual studio, but based on my current schedule, this will not get fixed anytime soon. I recommend you go ahead and resolve the warnings on your end.

Apologies about the issues. We will get to these as soon as possible. Please let us know if you have further questions.

Rahul

**Comment by chamber-wang** [comment]
Hi Rahul,

Thanks for your prompt reply, I've proposed the modification for this issue in following files.
And look forward to getting solution release soon of SIGPIPE  error handling. :100: 

\aws-iot-device-sdk-cpp\include\mqtt\Packet.hpp
\aws-iot-device-sdk-cpp\include\mqtt\Publish.hpp
\aws-iot-device-sdk-cpp\network\OpenSSL\OpenSSLConnection.cpp
