### ISSUE TITLE
What is the maximum clientID length?

### ISSUE THREAD

**Issue by PiedPieper** [aws/aws-iot-device-sdk-cpp#79]
Hi,

We are having small issues connecting with aws IoT with this SDK. When using a clientID that is 21 characters long, we are seeing collisions and getting kicked out even with different clientIDs.

Is there a maximum length? In the code there doesnt seem to be a #defined max size

Thanks!

**Comment by chaurah** [comment]
Hi @PiedPieper,
    Client ID max size is defined as 128. You can find the limits for AWS IoT on [this](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot) link. Please let us know if you have further questions.

Rahul

**Comment by PiedPieper** [comment]
@chaurah Perfect! Thanks!

**Comment by hedeshianaws** [comment]
Thank you for using AWS IoT. Please feel free to open a new issue if you have any further trouble with the SDK.
