### ISSUE TITLE
sync connect call gets stuck if reconnect is already running and succeeds

### ISSUE THREAD

**Issue by larsonmpdx** [aws/aws-iot-device-sdk-cpp#80]
my program is set up as an endless loop of sync calls.  if a packet is sent and fails this seems to trigger the internal reconnect logic, while my program goes into a timeout wait and then calls sync connect() after some time.  I've observed it getting stuck indefinitely if the reconnect is already running and succeeds right after the connect() call is made.  connect() then never returns.

Can you suggest a workaround for this?  Is it possible to disable the automatic reconnect stuff?  Or can you fix this race condition?

**Comment by vareddy** [comment]
Hi @larsonmpdx,
You can disable the autoreconnect logic by calling  `SetAutoReconnectEnabled(false)` for the [client instance](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/include/mqtt/Client.hpp#L336).
Let us know if that fixes the issue you are seeing. 
Thanks!
Varun

**Comment by larsonmpdx** [comment]
The issue happens randomly, I don't have a test case for it.  I can make the change but it'll be a few days before I know if it helped.  Can you read the code and figure out why it might deadlock?  I looked but it was hard to understand.

Are there any problems I might have with disabling auto reconnect?  Is it recommended to disable it in my case where I have a manual reconnect in an endless loop?

**Comment by vareddy** [comment]
Hi @larsonmpdx,
I will investigate the code to see where the deadlock happens. What is the flow that your application go through (connect, publish, timeout, connect, etc)? 
Since you are checking for failed sync calls and manually reconnecting, there should be no issues with disabling auto-reconnect in your case. 
Thanks!
Varun

**Comment by larsonmpdx** [comment]
all sync: disconnect, connect, publish in a loop until any error, on error timeout, then start over
