### ISSUE TITLE
Shadow::HandleGetResponse does not notify about Rejected responses

### ISSUE THREAD

**Issue by shekharhimanshu** [aws/aws-iot-device-sdk-cpp#86]
I noticed that [Shadow::HandleGetResponse](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/shadow/Shadow.cpp#L169) won't call the response handler registered by user when response type is `ShadowResponseType::Rejected`.

For example, when someone tries to call `PerformGetAsync` when no shadow exists. (should be fairly easy to reproduce). [Shadow::HandleUpdateResponse](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/shadow/Shadow.cpp#L209) handles the same case properly.

Something like below should fix the problem:
```
ResponseCode Shadow::HandleGetResponse(ShadowResponseType response_type, util::JsonDocument &payload) {
    if (ShadowResponseType::Delta == response_type) {
        AWS_LOG_WARN(SHADOW_LOG_TAG, "Unexpected response type for shadow : %s", thing_name_.c_str());
        return ResponseCode::SHADOW_UNEXPECTED_RESPONSE_TYPE;
    }
    
    ResponseCode rc = ResponseCode::SHADOW_REQUEST_ACCEPTED;
    if (ShadowResponseType::Rejected == response_type) {
        AWS_LOG_WARN(SHADOW_LOG_TAG, "Get request rejected for shadow : %s", thing_name_.c_str());
        rc = ResponseCode::SHADOW_REQUEST_REJECTED;
    else if (!payload.IsObject()
        || !payload.HasMember(SHADOW_DOCUMENT_STATE_KEY)) {
        rc = ResponseCode::SHADOW_UNEXPECTED_RESPONSE_PAYLOAD;
    } else {
        ...
    }

...

    return rc;
}
```

**Comment by vareddy** [comment]
Hi @shekharhimanshu ,
Thanks for finding this issue! As noted above, moving the payload validation into the if-else should solve the problem. I will make the fix internally and push to master after we test the fix.
Thanks!
Varun
