### ISSUE TITLE
Failing WSS handshake for session token

### ISSUE THREAD

**Issue by rdewein-letsdev** [aws/aws-iot-device-sdk-cpp#87]
I am integrating the aws iot cpp framework into our project and currently i am facing a failing wss handshake when trying to establish a websocket connection.

While searching for answers in other AWS IoT frameworks, i noticed that only the cpp framework doesn't do any HTML url encoding for the session token. 
When i do that encoding manually (before passing it to the API) everything works just fine.

Please let me know if you need some more information from my side.

**Comment by vareddy** [comment]
Hi @rdewein-letsdev
Thank you for your interest in the AWS IoT SDK. If you could provide a pull request of your changes, we will merge it into SDK after testing it internally. 
Thanks!
Varun

**Comment by vareddy** [comment]
Hi @rdewein-letsdev,
The pull request #88 has been merged. 
Thanks!
Varun
