### ISSUE TITLE
About  How to use 443 port connection

### ISSUE THREAD

**Issue by SunHeming** [aws/aws-iot-device-sdk-cpp#89]
thanks.
I have a question about use Openssl connection with port of 443。

now  I  used code of  "OpnesslConnection.cpp " to connection.  It default port is 8883  can connect  successful 。

But now  I want to  connection with port of 443 port .
How do I need to modify on the current basis to be able to successfully connect？
thanks

**Comment by vareddy** [comment]
Hi @SunHeming,
We are currently working on adding ALPN support (which is required to use port 443) to the OpenSSL network layer.  
I will keep this issue open and update it when we push the ALPN changes to master.
Thanks!
Varun

**Comment by vareddy** [comment]
Hi @SunHeming,
ALPN support has been added in [this](https://github.com/aws/aws-iot-device-sdk-cpp/commit/a2a6df1a99514a1bf17943560820f44cf4d6e1c5) commit. You can now use the additional constructor for the OpenSSL network layer to initialize ALPN (ie. when using port 443 for MQTT).
Please let us know if you have any more questions and if not close this issue. 
Thanks!
Varun

**Comment by SunHeming** [comment]
Thank you for your help.  I will colse this issue.
