### ISSUE TITLE
Publish simple message using aws-iot-cpp-sdk with Qt 

### ISSUE THREAD

**Issue by Nurhak** [aws/aws-iot-device-sdk-cpp#90]
Hello, I am trying to publish a simple message to aws-iot core with Qt. I have compiled the sdk and made a clean install. But when I am trying to use ConfigCommon::Initialize and some othe methods I get errors.

My Operating system is Linux.

Here is my .pro file

```
[QT += core
QT -= gui

CONFIG += c++11

TARGET = aws_test
CONFIG += console
CONFIG -= app_bundle

TEMPLATE = app

SOURCES += main.cpp

INCLUDEPATH += "/usr/local/include/" \
                "/home/nurhak/Desktop/aws-iot-device-sdk-cpp-1.3.0/common/"

LIBS += -L"/usr/local/lib/" -laws-iot-sdk-cpp
```

And Here is my code:
```
#include <QCoreApplication>
#include <QString>
#include <QDebug>
#include "mqtt/Client.hpp"
#include "mqtt/Publish.hpp"
#include "mqtt/Connect.hpp"
#include "mqtt/NetworkRead.hpp"
#include "NetworkConnection.hpp"
#ifdef USE_WEBSOCKETS
#include "WebSocketConnection.hpp"
#elif defined USE_MBEDTLS
#include "MbedTLSConnection.hpp"
#else
#include "OpenSSLConnection.hpp"
#endif

#include "util/logging/Logging.hpp"
#include "util/logging/LogMacros.hpp"
#include "util/logging/ConsoleLogSystem.hpp"

#include "ConfigCommon.hpp"
#include "PubSub.hpp"

using namespace std;
using namespace awsiotsdk;

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    std::shared_ptr<NetworkConnection> p_network_connection_;
    std::shared_ptr<mqtt::ConnectPacket> p_connect_packet_;
    std::atomic_int cur_pending_messages_;
    std::atomic_int total_published_messages_;
    std::shared_ptr<MqttClient> p_iot_client_;

    std::shared_ptr<awsiotsdk::util::Logging::ConsoleLogSystem> p_log_system =
          std::make_shared<awsiotsdk::util::Logging::ConsoleLogSystem>(awsiotsdk::util::Logging::LogLevel::Info);
      awsiotsdk::util::Logging::InitializeAWSLogging(p_log_system);

   awsiotsdk::ResponseCode rc = awsiotsdk::ConfigCommon::InitializeCommon("config/SampleConfig.json");



    return a.exec();
}
```
And The error:
```
/home/nurhak/qt_projects/aws_test/main.cpp:41: error: undefined reference to `awsiotsdk::ConfigCommon::InitializeCommon(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```

**Comment by vareddy** [comment]
Hi @Nurhak,
Thank you for your interest in the AWS IoT SDK!
 The SDK gets installed as `libaws-iot-sdk-cpp`. As can be seen from your .pro file, you are linking with `laws-iot-sdk-cpp`, which is incorrect. Could you change it to `libaws-iot-sdk-cpp` and check if that works?
Thanks!
Varun

**Comment by Nurhak** [comment]
Hello @vareddy,

Thank you for your reply after I try this I will turn back immediately.

**Comment by Nurhak** [comment]
Hello @vareddy , after I remove that lines , error doesn't change but the problem is about CommonConfig.hpp when I include the libraryI can see the methods but it doesn't have reference.

**Comment by vareddy** [comment]
Hi @Nurhak,
The ConfigCommon is not part of the library. You will have to compile with ConfigCommon.cpp. The [CMakeFiles](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/samples/PubSub/CMakeLists.txt#L40-L44) for the samples are a good example to follow on how to build your application.  I'm assuming in your case, for Qt, you will add the ConfigCommon.cpp into the list of sources that you compile. 
Let me know if that works for you.
Thanks!
Varun

**Comment by Nurhak** [comment]
Hello @vareddy ,

That works thanks for your help.
