### ISSUE TITLE
Does AWS IOT C++ SDK support publish binary data to Dynamo DB?

### ISSUE THREAD

**Issue by chamber-wang** [aws/aws-iot-device-sdk-cpp#98]
Hi All,

It seems that Python SDK support binary data publish by bytearray.
Does this also work in the C++ SDK as well? Thanks

**C++**
`                                          mqtt::QoS qos, const util::String &payload,
                                          ActionData::AsyncAckNotificationHandlerPtr p_async_ack_handler,
                                          uint16_t &packet_id_out);
`

**`# Python 2.7.x and 3.x**
`# Python 2.7.x and 3.x
filePath = "./fake/path/test.jpg"
openMode = "rb"  # Read as binary file
imageFile = open(filePath, mode=openMode)
imageData = bytearray(imageFile.read())
 
myAWSIoTMQTTClient.publish("topic/to/receive/image", imageData, 1)`

[https://forums.aws.amazon.com/thread.jspa?messageID=736619&#736619](url)

**Comment by vareddy** [comment]
Hi @chamber-wang,
The C++ SDK's Publish API requires the payload to be a String and cannot directly support binary data. The SDK relies on the string length function and this will behave unexpectedly if you have binary data with escape characters. 
You can try base64 encoding the binary data and storing it as a String.
Please let us know if you have any more questions.
Thanks!
Varun

**Comment by chamber-wang** [comment]
Hi @vareddy 

Appreciate for your answer. I will try this later.

Thanks!
Chamber Wang

**Comment by tolysz** [comment]
I am sending binary data(compressed payloads) it works just fine, the `std::string` does support binary, but you need to be careful and not use any c-string based functions (they might break it).
